### ISSUE TITLE
Find the rank of a user's points

### ISSUE THREAD

**Issue by harley** [merit-gem/merit#111]
Right now there is `Merit::Score.top_scored` which lists highest scored objects. Given an object's points, I'd like to know the rank of that object in terms of points.

Use case: On the leaderboard page, say a logged in user is at 18th on that list. I'd like to show the top 10 users (using top_scored), next a row of "...", then 17th, 18th and 19th users, and finally "..." again.

I'll look into the code when I have the chance again. Filing an issue because I'm not sure if it's worth implementing per @tute's opinion (see the first point in #61)

**Comment by gabrielguerin** [comment]
Hello @tute, I am not sure how to use your snippet... Where should I put it? And how can I use it in the frontend?
