### ISSUE TITLE
Access to user in a rule block 

### ISSUE THREAD

**Issue by polopi** [merit-gem/merit#147]
Hi there !
I would need to access the current_user in a rule block.
I saw that there was a pull request on it.
Will it be merged ?

**Comment by seanabrahams** [comment]
Here's my use case:

Imagine a commenting system. We want to subtract points from a commenter if their comment is deleted by a moderator (different user).

During the destroy process we assign the current_user to an attribute on the comment object, `comment.destroyed_by`. It's a hack that works, but it would be much nicer if you could access the current_user from the rule block.

**Comment by tute** [comment]
@seanabrahams that's a legit use case.

The main problems I had with the API is the arity of the blocks. Does Ruby 2 accept named parameters in blocks? In that case, we can resurrect PR #100 with syntax improvements, and drop support for Ruby 1.9.3, which is reaching EOL this month.

**Comment by tute** [comment]
[It does work with blocks](http://brainspec.com/blog/2012/10/08/keyword-arguments-ruby-2-0/)! `define_method(:foo) {| str: "foo", num: 1234| [str, num] }`.

I'd reconsider a rework of https://github.com/tute/merit/pull/100.
