### ISSUE TITLE
Using devise with the confirmable model causes User.id to be NULL

### ISSUE THREAD

**Issue by mjwb** [merit-gem/merit#164]
I am using Devise with the confirmable module. I followed the https://github.com/tute/merit/wiki/How-to-grant-badges-on-user-registration-using-Devise instructions and am able to create and display a badge on users/registration#update action. However, when creating a badge on users/registration#create action the correct insertions are made to the db but the user.id is set to null. I suspect this is because when using the confirmable option the user is not signed in (and as such no current_user object exists) until the account is confirmed via email link. The gem works  on the users/registration#create without the confirmable module.

**Comment by Arpsara** [comment]
Hi! I finally found the trick to make it work after the user confirm its account. The trick is to put the @confirmation = resource AFTER the super. Hope it will help.
