### ISSUE TITLE
How to create Badges by admin UI, rather then created in merit.rb initialize r  

### ISSUE THREAD

**Issue by anuj-dhanju** [merit-gem/merit#196]
I am working on education related app with mongoid. We have multiple admin for multiple organisations. Every admin want to create  own badges through UI. But i am not able to implement this thing . Because when i restart server all previous created badges automatically destroyed.

**Comment by Hoss3770** [comment]
Is there a way to make badges dynamic in Merit ? 
Or even add this to Merit in the feature.

**Comment by tute** [comment]
Merit won't be a good fit if you need dynamic badges. It assumes badges data is static, and reliability of its code depends on that. Badges are versioned alongside the rules that use them. Badges data live alongside the code in Merit.
