### ISSUE TITLE
BadgeRules: unexpected argument passed to the rule block

### ISSUE THREAD

**Issue by mdesantis** [merit-gem/merit#212]
I have the following scenario:
* badge rule:
```ruby
grant_on 'users#toggle_follow', badge: 'followers_1', to: :followed_pp do |merit_follow|
  merit_follow.followed_pp.user.followers_relation(User).size >= 30
end
```
* related controller#action:
```ruby
class UsersController
  # PUT /users/:id/toggle_follow
  # PUT /users/:user_id/toggle_follow
  def toggle_follow
    ...
    @user = MeritFollow.new current_user.player_profile,
                            @to_follow.player_profile
  end
end
```
* MeritFollow:
```ruby
MeritFollow = Struct.new(:follower_pp, :followed_pp)
```

This rule works without issues when the route used is `/users/:user_id/toggle_follow`, but raises an error when the route is `/users/:id/toggle_follow`, due to the fact that the argument passed to the block rule is not always the instance variable set in the action (`@user` in this case).

If the rule has `model_name` set or the action is in a controller which corresponds to a model and the action has a `params[:id]` set and a record is found using these datas, the instance variable is ignored and the argument passed is the record found previously.

This happens because `Merit::BaseTargetFinder` has this instructions:

```ruby
def find
  get_target_from_database || reanimate_target_from_action
rescue => e
  Rails.logger.warn "[merit] no target found: #{e}. #{caller.first}"
end

def get_target_from_database
  model_class.find_by_id(@action.target_id)
end

def model_class
  klass_name = (@rule.model_name || @action.target_model).singularize
  klass_name.camelize.constantize
end
```

A work around for this issue is to set `params[:id] = nil` at the and of the action:

```ruby
class UsersController
  def toggle_follow
    ...
    @user = MeritFollow.new current_user.player_profile,
                            @to_follow.player_profile
    ...
    # Hack for Merit
    params[:id] = nil
  end
end
```

 * * *

I see two problems here:

1. It isn't documented. In the README this feature isn't written anywhere (or at least I didn't find it); I had to dive into the code in order to understand this behaviour and find that it is different from the documentation
2. It is not possible to disable it: I really don't want Merit trying to infer the target object from the controller name and `params[:id]`: this is so magic that can lead to undesired behaviours just changing a route or a controller name, and forces me to do *magic* hacks like `params[:id]`. I just want to set it explicitly using the instance variable

**Comment by tute** [comment]
The only mention to this in the README is a confusing:

> `:model_name` define the controller's name if it's different from the model's (e.g. `RegistrationsController` for the `User` model).

"controller's" and "model's" are mixed up.

I appreciate your feedback, and I'm interested in improving this, making that find more explicit when needed. But how exactly? If an application defines more than one instance variable, which one should merit choose?

**Comment by mdesantis** [comment]
Ok, I tell my thoughts about it:

1. First issue: in the README there is no mention about the `model_name|controller_name/params[:id]` target inferring without instance variable, and no mention about the targets spotting precedence (if the inferred target is found, the instance variable is ignored). I think that the target spotting logic deserves a paragraph; I would write something like this (disclaimer: english is far from being my mother tongue, so please make the due corrections):

  > Badges can be automatically given to any resource in your application based on rules and conditions you create. Badges can also have levels, and be permanent or temporary (A temporary badge is revoked when the conditions of the badge are no longer met).
  >
  > *The target of a badge rule is the object against the rule is applied and against which the badge will be processed. The target is inferred by the model name if specified or by the controller name and `params[:id]`, and if it is not found the value of the instance variable whose name is inferred by the model name if specified or by the controller name will be used. If none of these methods succeed in finding the target, Merit will log a `no target_obj` warning and the rule processing will stop.*
  >
  > [...]
  >
  > * *`:to` the target's field to give the badge to. The target is calculated using the logic above.* [...]

2. Second issue: allow `model_name|controller_name/params[:id]` target inferring disabling, making Merit use only instance variables (I can't find a good name for the option: something like `target_inferring_from_action = true|false`? `use_target_data_only = true|false`?). I don't think a per-rule option is needed, I would go for a Merit config option. I would like to disable it and control Merit only through instance variables, as I said leaving it on would possibly lead to undesired behaviours (like the one occurred to me).

**Comment by tute** [comment]
On the 2nd suggestion, I believe the `grant` APIs should expose everything. A configuration adds complexity, merit would start to be modal, behaving one way or the other according to some flag that's not obvious while looking at the code because it's in `config/` and not `app/`. It's also a sign that I (or rather we) couldn't decide on what is "the" best way to solve this issue, and so let users choose, instead of the library taking the decision for them and deciding on a good API. If we needed different strategies, merit should be extendable, so users could plug in their own implementations on how to fetch the target object.

Also, if we act on instance variables and an application exposes three or four instance variables, how does merit know which one to choose?

On the 1st suggestion, I like your improvement to the README, and will add it in. Thank you for improving that explanation!

**Comment by mdesantis** [comment]
I agree about the `grant` API consideration, it's good that you think at the best thing to do for the product :)

> if we act on instance variables and an application exposes three or four instance variables, how does merit know which one to choose?

I didn't understand this point: what is it going to change about instance variables?

**Comment by tute** [comment]
> > if we act on instance variables and an application exposes three or four instance variables, how does merit know which one to choose?
> I didn't understand this point: what is it going to change about instance variables?

If we disable target inferring (`model_name` or `controller_name`), and your controller action defines `@user`, `@profile` and `@title`; how does Merit know which acts as target object?

**Comment by mdesantis** [comment]
Instance variables name inferring is not the problem in this case; the problem is that Merit uses `params[:id]` when the instance variable is not defined; I would like an _instance variables only_ mode, so I can avoid the `params[:id] = nil` hack :)

The name inferring is an interesting question, but maybe it deserves another issue.
