### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by pingram** [merit-gem/merit#222]
Has anyone run performance tests on Merit? We're strongly considering using it, but the after_filter on all controller actions worries me slightly. If you have any numbers, please let me know!

**Comment by tute** [comment]
I don't know of any performance tests with merit, but you can always disable the reputation computation in the `after_filter` with the [`checks_on_each_request`](https://github.com/merit-gem/merit/blob/master/lib/generators/merit/templates/merit.rb#L3-L4) configuration option, and [compute them in a background job](https://github.com/merit-gem/merit/wiki/How-to-set-rankings-%28and-reputation-in-general%29-in-the-background%3F).

**Comment by pingram** [comment]
Thank you first of all for the quick reply! It seems that even if you have the `checks_on_each_request` flag, it will still check all the rules and log the merit action if any match. Is that correct? This too could take a little while since it is being processed on each controller action. It's definitely great to be able to process the rules later.

**Comment by tute** [comment]
> It seems that even if you have the `checks_on_each_request` flag, it will still check all the rules and log the merit action if any match. Is that correct?

That's correct. Suggestions on how to make it faster (with benchmarks of course! :) ) are welcome.

Does Rails send the response before or after `after_filter` callbacks run?

**Comment by pingram** [comment]
I may benchmark it on our app if we decide to go with it, and of course I'll share that data : )

My understanding of after filters is that they are executed at the very end of a controller action, but not before the action returns. From the [doc](http://guides.rubyonrails.org/action_controller_overview.html#after-filters-and-around-filters):
> "After" filters are similar to "before" filters, but because the action has already been run they have access to the response data that's about to be sent to the client. Obviously, "after" filters cannot stop the action from running.

**Comment by tute** [comment]
Thanks for your input. Closing as it's not an open issue with merit, feel free to continue discussion!
