### ISSUE TITLE
[Badges] dummy app problem?

### ISSUE THREAD

**Issue by lszeremeta** [merit-gem/merit#223]
Hi,

I wanted to look at the test merit app...

```
git clone https://github.com/merit-gem/merit.git
cd merit/test/dummy/
bundle install
rake db:migrate
rails s
```
I added the user and tried to add a comment. I typed the required data (including user name I created earlier) and got the following error:

NoMethodError in CommentsController#create
**undefined method `comments' for nil:NilClass**

Extracted source:
              
      # If it has 10 comments, grant commenter-10 badge, find badge by badge_id
      grant_on 'comments#create', badge_id: 1, level: 10 do |comment|
        comment.user.comments.count >= 10
      end
      # Testing badge granting in more than one rule per action with different targets
      grant_on 'comments#create', badge: 'has_commenter_friend', to: :friend do |comment|

Rails.root: /***/merit/test/dummy

Application Trace | Framework Trace | Full Trace
app/models/merit/badge_rules.rb:47:in `block in initialize'
Request

Parameters:

```
{"utf8"=>"✓",
 "authenticity_token"=>"YrNWeA3hRQyG4KrScs1Xe/NcFTwBy9vp5NFof0mrv4Djp91V2iQU3R+PQ6ChEqI9HbR8JLAcwhkOkFGv7KpAvw==",
 "comment"=>{"name"=>"Test comment",
 "comment"=>"Test text",
 "user_id"=>"test2"},
 "commit"=>"Create Comment"}
```

Toggle session dump

```
_csrf_token: "gRSLLdfFUdGZb+ly09/1Ru7oaRix1xnw6kE50KUB/z8="
flash: {"discard"=>[], "flashes"=>{"notice"=>"Comment was successfully created."}}
session_id: "cdc162a2baca1c1d30ca101f46c37c77"
```

Ruby: 2.2.2
Rails: 4.2.1

**Comment by tute** [comment]
You might need to run `rake db:reset`, or `rake db:seed`, to have seed data. After that you can add a tenth comment, edit your name, etc, and see how reputation changes. Please let me know if this solves your issue (and if we should improve https://github.com/merit-gem/merit/blob/master/TESTING.txt).

Thanks for your input!

**Comment by lszeremeta** [comment]
Thanks @tute for your reply.
My very, very stupid mistake - I typed user name instead of user id when I added new comment. :smile: 

![merit dummy app](https://cloud.githubusercontent.com/assets/5364674/7402754/67c00196-eecf-11e4-87ec-843597051ab6.png)

So everything works perfect :smile: 
Sorry for the trouble.

**Comment by tute** [comment]
Glad to hear!
