### ISSUE TITLE
Observing multiple meritable models

### ISSUE THREAD

**Issue by gauravtiwari** [merit-gem/merit#225]
Hi @tute 

How to watch multiple meritable models for changes? In readme, it uses User model but, what if there are more than 1 meritable model?

Can merit models be overriden to use rails callbacks feature instead of observers?

**Comment by tute** [comment]
From the unique `changed_data[:sash_id]` value you should be able to grab the related model:

```ruby
resource = User.where(sash_id: changed_data[:sash_id]).first ||
  Admin.where(sash_id: changed_data[:sash_id]).first ||
  Car.where(sash_id: changed_data[:sash_id]).first
```

**Comment by gauravtiwari** [comment]
thanks @tute . I knew this approach but wanted to avoid it as it's gets messy when conditions increases.  

Can we store sash_type and then this would make things easier and cleaner ?

```ruby
resource = sash_type.constantize.where(sash_id:  changed_data[:sash_id])
```

**Comment by tute** [comment]
`Sash` intentionally doesn't know about the classes in your system, and the only link it has are the `sash_id` in your model(s). That's the cleanest way of attaching reputation to existing applications that I could find. We used to have more intersection between merit and the app, and that made it harder to install, upgrade and uninstall.

I'm willing to discuss how can we make it more comfortable with you without losing much (if any) this convenience and simplicity.
