### ISSUE TITLE
Apartement exclude merit models

### ISSUE THREAD

**Issue by nabilaSillaps** [merit-gem/merit#228]
I use Merit and I have added apartment for multitenancy. I want to exclude the merit models and tables.

the following line generates an error:

config.excluded_models= {Merit::Badge}
undefined method `table_name' for Merit::Badge(id, name, level, description, custom_fields)

Thanks for your help.

**Comment by tute** [comment]
That's because `Merit::Badge` is an `Ambry` model (in memory), and not `ActiveRecord`. You don't need to define it as excluded model, but this means that every instance of your app needs to know all the badges as of now.
