### ISSUE TITLE
Adding badges and rules at runtime

### ISSUE THREAD

**Issue by VVine** [merit-gem/merit#229]
Hi,

I'm an early ruby dev so excuse me if this is obvious. I want to develop a course system for a school project with an undefined number of courses, that can change at runtime. Is it possible to add badges and rules to that? Where would I put this?

**Comment by tute** [comment]
As of now, badges information are stored in an initializer, and loaded only in memory. There is no way, as of now, to add badges at runtime.
Thanks!
