### ISSUE TITLE
NoMethodError undefined method `current_user'

### ISSUE THREAD

**Issue by scottklarose** [merit-gem/merit#230]
I'm using merit (2.3.2) in my Ruby on Rails application (Rails Version 4.1.1) and keep getting a `NoMethodError` every time one of my badge rules are triggered.  The application is a RESTful API I am using as a backend for a mobile application.  I am **NOT** using Devise as the application is an API and has no views.  The issue happens regardless of what `controller#action` I pass in and continues to happen even after specifying an object with the `:to` field.  Bellow I have provided the stack trace that is produced when a badge is rewarded:

    NoMethodError (undefined method `current_user' for #<Api::UserController:0x007fc45cd7f5a0>):
      merit (2.3.2) lib/merit/controller_extensions.rb:23:in `merit_action_hash'
      merit (2.3.2) lib/merit/controller_extensions.rb:18:in `log_merit_action'
      merit (2.3.2) lib/merit/controller_extensions.rb:9:in `block in included'

Am I missing something here? The installation section of the **README.md** never specifies that all controllers must have a `current_user` method.  Please let me know if you require any additional information to solve this issue.

**Comment by tute** [comment]
merit needs to know who is performing the actions. You can configure how it searches for the user with the `current_user_method` config (https://github.com/merit-gem/merit/blob/master/lib/merit.rb#L37-L41).

How does your API know who is authenticated? That's what you should put there. We should add a section to the README specifying this, if it's not there yet.

**Comment by scottklarose** [comment]
I configured the `current_user_method` but am getting an error when I try to add the badge.  It seems that merit doesn't support user ids that are UUIDs.  Is there a quick fix for this or should I manually make the changes inside the migration files?

**Comment by tute** [comment]
You have to change the migrations in your application to change the type of the foreign key.

**Comment by scottklarose** [comment]
Thanks that really helped. Awesome gem great job on the upkeep!
