### ISSUE TITLE
Merit Not Finding target_object

### ISSUE THREAD

**Issue by scottklarose** [merit-gem/merit#231]
I'm experiencing some odd behaviour surrounding the `model_name` parameter and can't find anything in the documentation, `README.md` or previous issues that has helped.  For some reason merit is having issues finding the `target_object` within the rule block.  When I don't use the `model_name` parameter the `target_object` returned is incorrect. 

    grant_on ['api/location#create', 'api/location#delete_location'], badge: 'Well-Traveled', temporary: true do |location|
        puts location.name
        true
    end

Produces the following error:

    NoMethodError (undefined method `name' for true:TrueClass): app/models/merit/badge_rules.rb:61:in `block in initialize'

When I set the `model_name` parameter, merit returns a reference to the `@location` variable within the location controller regardless of the value I pass as the `model_name`.

    grant_on ['api/location#create', 'api/location#delete_location'], badge: 'Well-Traveled', temporary: true, model_name: 'User' do |user|
        puts user.name
        true
    end

This prints the name of the location and not the user's name.  If I pass any model name it always returns a reference to the location instance variable.  All of my controllers are contained within an API folder, could this be what's messing up the method that finds the `target_object`?  Do I have to add something to my `routes.rb` to allow for merit to find the models folder?

**Comment by tute** [comment]
See this discussion to see how target_object works: https://github.com/merit-gem/merit/issues/137#issuecomment-35350693. In a nutshell, merit expects a `LocationsController` to return a `@location #=> Location` object. From there you can get to your user with `to: :user`.

**Comment by scottklarose** [comment]
From #137 I see that there are issues with controllers within a namespace which would explain why I was getting the `NoMethodError` and `[merit] no target found: uninitialized constant Api::Location.` when I had the following rule: 

    grant_on ['api/location#create', 'api/location#delete_location'], badge: 'Well-Traveled', temporary: true do |location|
        puts location.name
        true
    end

But why does specifying a `model_name` return the `@location` variable?  Shouldn't it look for an instance variable within the location controller that is of the same name specified by the `model_name`.  I was under the impression from looking at https://github.com/merit-gem/merit/issues/137#issuecomment-35195365 and `base_target_finder.rb` that that's how it worked.

Regardless, I did try the rule with the `to: :user`:

    grant_on ['api/location#create', 'api/location#delete_location'], badge: 'Well-Traveled', temporary: true, model_name: 'User', to: :user do |user|
        puts user
        true
    end

But for some reason it user is a reference to `@location`.  Does the Location model need to belong to User?

**Comment by tute** [comment]
Can you show the controller code too please?

**Comment by scottklarose** [comment]
For sure anything that helps.  

api/location#create:

    def create
        @user = User.find_by_id(params[:id])

        @location = Location.new()
        @location.name = params[:name]
        @location.location_type = params[:type]
        @location.description = params[:description]
        @location.address = params[:address]
        @location.phone_number = params[:phone_number]

        if params.has_key?(:coverToUpload)
          @location.cover_image = params[:coverToUpload]
        end

        if params.has_key?(:logoToUpload)
          @location.logo_image = params[:logoToUpload]
        end

        @location_owner = @location.location_owners.new()
        @location_owner.owner_id = params[:id]

        respond_to do |format|
          if @location.save
            @user.increment!(:locations)
            @user.save

            response = {:status => "201", :message => "Location successfully created."}
            format.json { render json: response, status: :created }
          else
            format.json { render json: @location.errors, status: :unprocessable_entity }
          end
        end
      end

I have only tested this badge rule on creating the Location and not deleting it so I will only post the create method.  If you require me to post anything else please let me know and I can provide the complete controller code or any other relevant methods.

**Comment by tute** [comment]
It looks like you don't use the instance variables for rendering views. Because of how merit infers objects and who acts on them, if you don't define the `@location` as an instance but a local variable (remove the at sign) I believe it should start working well, with the `model_name: "User"` version of the rule.

**Comment by scottklarose** [comment]
Should I change `@user` to a local variable as well?

**Comment by tute** [comment]
That one doesn't interfere with merit, but you could. I personally always keep scope as constrained as possible, so I'd do it.

**Comment by scottklarose** [comment]
ok thank you for your continued support I will make the changes and close the issue if it works.

**Comment by tute** [comment]
Thanks!

**Comment by scottklarose** [comment]
Hey man really sorry should have responded sooner I have just been crazy busy with the July 1st celebrations here in Canada.  

When I remove the `@location` and change it to just `location` I get an error from merit saying that it can't find the `@location` variable inside `location_controller.rb`.  The badge is never added to the user and the code inside the rule block is never executed. What could be causing this?  Please reopen this issue as I suspect there may be an actual problem with how merit works with APIs.

**Comment by tute** [comment]
Do you intend to grant the badge to the `current_user`? Does `to: :action_user` work for you in that case?

Also, why do you get `uninitialized constant Api::Location`? Is your controller singular named, and namespaced into `Api`? Can you post the class definition, or all of it?

**Comment by scottklarose** [comment]
Im currently implementing unit tests, upgrading to rails 4.2.3 and refactoring a bunch of code.  I suspect there is an issue with how my associations are set up that are causing this issue with merit.  Will let you know after I finish in a couple days if anything has changed.

**Comment by tute** [comment]
As this doesn't seem like a bug with merit I'll leave it closed. Regardless, let's continue discussion in this thread until we make it work.
Best!
Tute.

**Comment by scottklarose** [comment]
Yeah I suspect it may have to do more with my application then merit its self.  Good call on closing the issue will let you know if it continues after the refactor.  Thanks for the continued help!

**Comment by scottklarose** [comment]
Hey @tute I'm still having issues integrating merit into my project, specifically with finding the `@user` variable within my `Api::LocationController`.  The `model_name` parameter doesn't seem to have any effect as the only instance variable returned seem to be the one with the same name as the controller.  Let me know if you think you can help out and I will provide you with more information.

**Comment by tute** [comment]
Why do we have in your controller `@user = User.find_by_id(params[:id])`? Wouldn't that be your `current_user`, or similar? Otherwise, any user can create locations for any users? And, if it is the `current_user`, can you use the merit option `to: :action_user`?

The code that finds the target object to grant reputation to is in: https://github.com/merit-gem/merit/blob/master/lib/merit/target_finder.rb

**Comment by scottklarose** [comment]
Yes that is my `current_user`.  The problem isn't finding the `current_user` or who to grant the badge to its that I can't get a reference to the model selected with `model_name`.  

I have a badge rule that gets triggered when the create or delete methods are called within the `LocationController`.  The `LocationController` has a reference to `@user` (which is the `current_user`).  When the rule is triggered I need to check a value stored within the `current_user` to see if the user is eligible for the badge.  The `model_name: 'User'` parameter should return the reference to `@user` within the `LocationController` should it not?

I'm sorry I may not be explaining this very well I am fairly inexperienced with Rails and have little to no experience debugging gems.

**Comment by tute** [comment]
Send you a tweet inviting us to do a pairing session to sort this out. :+1:
