### ISSUE TITLE
How merit finds the target object if controller name is not the object target name and there is no :id param?

### ISSUE THREAD

**Issue by caiqinghua** [merit-gem/merit#233]
# 1. It worked successfully
```ruby
score 10, on: 'checkout#update', model_name: 'Spree::Order'
```
It worked successfully.
User.find(3).points 130
User.find(3).points 140

# 2. add target_object
```ruby
      score 10, on: 'checkout#update', model_name: 'Spree::Order' do |order|
        order.completed?
      end
```
it worked fail.
User.find(3).points 140
User.find(3).points 140
log:
```ruby
[merit] no target found: uninitialized constant Checkout. /Users/caiqinghua/.rvm/gems/ruby-2.2.1/gems/merit-2.3.2/lib/merit/base_target_finder.rb:13:in `find'
```

# 3. The checkout load @order code
```ruby
    def load_order_with_lock
      @order = current_order(lock: true)
      redirect_to spree.cart_path and return unless @order
    end
```

# 4. there are two way to get target_object
https://github.com/merit-gem/merit#how-merit-finds-the-target-object
a. searches for the instance variable
b. If the rule had the :model_name option specified, found by the :id param

# 5. how to solve the problem?
a. The Spree::Order is not equal the controller name:checkout.
b. There are no :id in the param
So, how solve the problem?
Is it support find target_object by custom define method?
if not, can we solve this problem by custom define target_object_method?
like this:
```ruby
score 10, on: 'checkout#update', model_name: 'Spree::Order', target_object_method: current_order do |order|
        order.completed?
      end
```

**Comment by caiqinghua** [comment]
I have solved this problem， can i PR to master branch?

**Comment by tute** [comment]
Sure, please send the PR so I can understand better what your problem and solution look like. Thank you!
