### ISSUE TITLE
Monthly rank based on points

### ISSUE THREAD

**Issue by ACPK** [merit-gem/merit#235]
What is the best way to provide the user with their rank based on their accumulated points for the month?

**Comment by tute** [comment]
See https://github.com/merit-gem/merit/issues/61#issuecomment-13992156 for sample code, without the month requirement. `merit_score_points` and `merit_activity_logs` are two tables that have timestamps, to add that filtering. See more about them in: https://github.com/merit-gem/merit/wiki/General-merit-workflow.
Thanks!
