### ISSUE TITLE
why check the id if model_name is passed?

### ISSUE THREAD

**Issue by hw676018683** [merit-gem/merit#236]
is there something wrong if not checking?
```ruby
    def check_active_record_id(id)
      id.to_s =~ /^[0-9]+$/
    end

    def check_mongoid_id(id)
      id.to_s =~ /^[0-9a-fA-F]{24}$/
    end
```
i was confused with that, because i used auto incrementing id in mongodb.
failing to ` id.to_s =~ /^[0-9a-fA-F]{24}$/`.
is it possiablely canceled?

**Comment by tute** [comment]
The code is not prepared for that as of now.

**Comment by hw676018683** [comment]
I can't understand the means.
Can you explain it more?

**Comment by tute** [comment]
I mean that merit is not prepared to work with a mongodb database with auto incrementing, integer ids. If the solution is simple I wouldn't mind merging it into merit, but if it's not, I'd rather do it as an extension in another repository, and do the appropriate modifications in merit to allow for that.
Thank you!

**Comment by hw676018683** [comment]
Thank you for the answer.
But is there something wrong to delete the check. I'm very confused with this.
Can you explain it more for me ?
thx

**Comment by tute** [comment]
I don't think there is. I think the issue was to allow for frendly id slugs, but that check in active record made normal mongo id checks fail, so then we split them. If you remove that, I don't think you'd encounter new bugs (at least that I am aware of).
