### ISSUE TITLE
Accessing current_user in a rule block

### ISSUE THREAD

**Issue by fedemoretti** [merit-gem/merit#239]
Hello, I currently have 2 models: 
- User, which has many Checkins (User can do checkins)
- Checkin, which has many Users (Checkins can have many attendants)

What I want to do, is grant a badge to User when he has more than 3 checkins.

So I defined my badge, I created the grant_on, but inside the block I can't find a way to access the current user.

The action I'm calling is `checkins#create` and I want to check that `current_logged_in_user.checkins.count > 3`

This is my `badge_rules.rb`
```ruby
grant_on 'checkin#create', badge: 'party-freak' do
  current_logged_in_user.checkins.count > 3
end
```
I'm getting undefined method for "current_logged_in_user" which is a method in my ApplicationController. Should I have to define it somewhere else? I'm not using Devise, just custom authentication.

Thanks in advance, please let me know if I need to clarify anything.

**Comment by tute** [comment]
Indeed this is not possible as of now. This was requested long ago, I tried to do it in https://github.com/merit-gem/merit/pull/100. At the moment the API felt funky, but now it's possible thanks to keyword arguments. See: https://github.com/merit-gem/merit/issues/147#issuecomment-74172263.

This is a very valid feature request, and I don't have time to work through it myself though for a while. I'll be happy to review a PR and work through it until it's merged. Thanks!

**Comment by tute** [comment]
As a workaround, you can use `add_badge` in the controller action: https://github.com/merit-gem/merit/#other-actions

**Comment by fedemoretti** [comment]
Thanks for your answer! I'm pretty new to Rails but I'll take a look at the code and see what I can do.

**Comment by tute** [comment]
Closing in favor of PR https://github.com/merit-gem/merit/pull/240. Thank you!
