### ISSUE TITLE
Cleanup of merit_actions ?

### ISSUE THREAD

**Issue by rept** [merit-gem/merit#241]
Hi,

First of all thanks for this gem, never would have dreamed there would be a gem specifically for badges, points, etc :-)  Also no open issues and 1 open PR and 66 closed, confidence inspiring, well done!

I'm working on implementing this gem but want to be careful in respect to performance and data needed.  

At the moment I'm doing checks to give badges based on the creation of an object.  For example a badge: night owl, if the user created the object at night.

I saw that even if the badge was already given, the merit_action table gets filled and in target_data a copy of the object is kept.  Probably because merit is able to recalculate reputation according to the wiki.  In my use case I would only need 2 attributes of the object, where at this time the complete object is kept.  I expect users to create about 20 object a day so while this isn't enormous I'm wondering if there is a way to only keep the minimum.  Also: would there be a way to cleanup the merit_actions table after some time (for example after 3 months...)?  I wouldn't mind to loose the possibility to recalculating reputation if that would allow me to do a cleanup.

**Comment by tute** [comment]
You can drop all the information in merit_actions periodically, and the only thing you lose is ability to recompute. Back ups take care of everything, so you should be fine.

Thanks for your question!
