### ISSUE TITLE
Multi company scores

### ISSUE THREAD

**Issue by rept** [merit-gem/merit#242]
Hi,

I'm trying to get the following to work and wonder what the best practise would be.

In my application Users belong to a company and there are many companies in the system.

I would like to create score boards per company. I would also like to get a score board per week.

Scores don’t seem to have custom_fields like Badges do.  So to be able to get all scores for a certain week/company I would have to iterate over the users of that company and get those scores into an array together with the user id.  Is there an easier way to do this?

I was thinking maybe adding the company_id to the category of the score.  This could also be done for weeks.  That way I could do 

    Merit::Score.where(:category => 'scores_' + company_id + '_' + week)

To get the scores of a company and for a certain week.  Not sure if this is the correct way to go though.

**Comment by tute** [comment]
> To be able to get all scores for a certain week/company I would have to iterate over the users of that company and get those scores into an array together with the user id. Is there an easier way to do this?

You make it sound hard, but that's precisely the problem that relational databases solve efficiently. What database engine are you using? Do you know SQL? What is your data model, exactly?

**Comment by tute** [comment]
If you want, you can share your `db/schema.rb` file so we build up the query you need.

**Comment by rept** [comment]
Hi @tute,

Thanks for offering your assistance.  I'm using Postgresql and I'm proficient in querying, that's not the issue.

I was just wondering if that is the correct way to do this?  By including the week in the category I feel like I could be limiting myself later.

This is the query that works.

    select users.id, sum(num_points) as points from users 
    inner join companies on company_id = companies.id
    inner join sashes on users.sash_id = sashes.id
    inner join merit_scores on merit_scores.sash_id = sashes.id
    inner join merit_score_points on score_id = merit_scores.id
    where category = 'timesheet_week' + week
    group by users.id

Are there any plans to add custom fields to scores as well?  That way I could add the year and week number.  (can't use created because it's possible somebody gets points now for next week.

**Comment by tute** [comment]
That looks good! I massaged it a bit (we group by companies not users, right? And some syntax):

```sql
-- Score boards per company
-- Score board per week
SELECT users.id, SUM(num_points) AS points FROM users
  INNER JOIN companies ON users.company_id = companies.id
  INNER JOIN sashes    ON users.sash_id = sashes.id
  INNER JOIN merit_scores ON merit_scores.sash_id = sashes.id
  INNER JOIN merit_score_points ON merit_score_points.score_id = merit_scores.id
WHERE category = 'timesheet_week_' + week
GROUP BY companies.id;
```

You can use the `category` entry to identify weeks, but I'm sure there's a better way computing weeks for `created_at` timestamps in SQL. Let's improve this solution! Let me know how it continues.

> Are there any plans to add custom fields to scores as well?

I don't plan to add that. You have to convince me that it's the only and best way to implement functionality into your application, and until now this doesn't seem to cut it.

Thanks for your input!

**Comment by rept** [comment]
Hi tute,

I need the grouping by user because I want to make a list of scores for a current week by user.  Users can't see what's happening in other companies.  So you're right, the query needs a company_id added to the where clause (but not to the group clause in my case).

I also tried adding something like this to the Company model, but struggling with that:

```ruby
has_many :points, through: :users
```

That didn't work, neither did this:

```ruby
has_many :points, -> { joins(users: {:sash => :merit_scores } ) }
```

So at the moment I added this to the Company model which works:

```ruby
def points
  self.users.joins('join merit_scores on users.sash_id = merit_scores.sash_id')
  .joins('join merit_score_points on score_id = merit_scores.id')
  .select('users.id', 'sum(num_points) as points').group('users.id')
end
```

This allows me to get the score list for a company pretty easy like this:

```ruby
@company.points.where('merit_scores.category' => 'timesheet_week_' + week)
```

About the custom fields.  Well I can certainly work around it but putting it in the category string and query.

**Comment by tute** [comment]
This looks good. Do you still have a standing problem that you need to solve, or this covers your needs?

**Comment by rept** [comment]
Nope I'm good thanks for the assistance.
