### ISSUE TITLE
Disable merit for some users

### ISSUE THREAD

**Issue by rept** [merit-gem/merit#244]
Hi,

I want to offer gamification as an option.  For users that don't want it, I also don't want the overhead of running all the queries to determine if points or badges need to be created.
Am I correct to assume that I can just use put an if statement around the score and grant_on statements in the initialize of BadgeRules and PointRules?  Or is there a better way?

**Comment by rept** [comment]
I solved this by checking it in each grant_on

```Ruby
      grant_on ['content#create', 'content#update'], badge_id: 3, to: :user do |ts| #Novelist
        ts.user.gamification && ts.notes.length >= 200
      end
```

Don't know if there's a more efficient way.

**Comment by tute** [comment]
This solution is good. Thanks!
