### ISSUE TITLE
How to get badge id from observer?

### ISSUE THREAD

**Issue by robypez** [merit-gem/merit#245]
Hello everybody, we are using Merit for badges in out CMS.
I need to add notifications, and in my notification I need to add some custom attributes I added during badge creation (for example image).
How can I get badge id in the observer?

**Comment by haizop** [comment]
It is available via the changed_data hash:

changed_data[:merit_object][:badge_id]

**Comment by tute** [comment]
Indeed. Thank you both, if you think we can improve docs let's discuss in a PR. Thank you!
