### ISSUE TITLE
Fix Ruby warnings

### ISSUE THREAD

**Issue by tute** [merit-gem/merit#246]
`RUBYOPT=-w rake` runs all tests with ruby warnings enabled, which are printed out in [stderr](https://robots.thoughtbot.com/input-output-redirection-in-the-shell). They are very noisy, as it shows warnings for every dependency in use alongside the tests output, so they are most useful when filtering only the warnings coming from this gem. We do that redirecting tests `stdout` to `/dev/null` (ignoring it), and redirecting `stderr` to `stdout`, with the following command:

```bash
RUBYOPT=-w rake 2>&1 1>/dev/null | grep merit | sort --unique
```

The output is:

```
/.../merit/lib/merit/controller_extensions.rb:50: warning: instance variable @user not initialized
/.../merit/lib/merit/controller_extensions.rb:50: warning: instance variable @user not initialized
/.../merit/test/dummy/app/models/merit/point_rules.rb:39: warning: ambiguous first argument; put parentheses or a space even after `-' operator
```

Merit should run without any warnings.

**Comment by yakschuss** [comment]
@tute  - let me know if there's any further action I can take to help with this issue.

**Comment by tute** [comment]
Yes, thanks! Will close this issue in favor of your PR: https://github.com/merit-gem/merit/pull/247.
