### ISSUE TITLE
Trying to access current_user instead of @user

### ISSUE THREAD

**Issue by jpaulo** [merit-gem/merit#249]
Hello,

first of all, i am sorry if this is not a bug or if it is a problem with my app, and i appreciate the help.
I am trying to give a "welcome" badge to user when a sign up action occurs. The badge_rules file looks like this.

<pre>
      grant_on 'v1/auth/users#signup', badge_id: 1, model_name: 'User', to: :itself do |user|
        user.persisted?
      end
</pre>

But this error keeps occuring

<pre>
F, [2016-03-28T17:18:56.789485 #30165] FATAL -- : 
ForbiddenError (ForbiddenError):
  app/controllers/v1/base_controller.rb:41:in `current_user'
</pre>

That's is because merit gem is trying to access my "current_user" method that looks like this

<pre>
    def current_user
      raise ForbiddenError if @current_user.nil?
      @current_user
    end
</pre>

But i want it to access the variable @user. What am i doing wrong?
Thanks in advance.

**Comment by tute** [comment]
For this particular case, you can remove the `, to: :itself`, which makes merit read from `current_user`, and it will then use the instance variable as you'd expect (provided it's named `@user`).

I personally find it weird that you raise on no current_user, but that's another topic. :)

**Comment by jpaulo** [comment]
Thank you very much for your help, @tute. Yes, the instance variable's name is @user and the user is created successfully. I made changes in the code based on your suggestion and the error remains. It is still trying to get current_user instead of @user.

<pre>
grant_on 'v1/auth/users#signup', badge_id: 1, model_name: 'User' do |user|
  user.persisted?
end
</pre>

Raising here is probably not necessary, you are right. :)

**Comment by tute** [comment]
Can you paste the content for that controller, and its parent controller? Thanks!

**Comment by jpaulo** [comment]
For sure! The relevant parts are...

users_controller.rb
<pre>
      before_action :authenticate_user!, except: [login, signup]

      def signup
        @presenter = SignupPresenter.new

        @user = ::User.new(signup_params)
        @validation = TokenService.new(@user)
        @auth_token_service = UserAuthenticationTokenService.instance
.......
       @presenter.user = @user
        render @presenter.to_h
</pre>

base_controller.rb
<pre>
    def current_user
      raise ForbiddenError if @current_user.nil?
      @current_user
    end
</pre>

badge_rules.rb
<pre>
module Merit
  class BadgeRules
    include Merit::BadgeRulesMethods

    def initialize
      grant_on 'v1/auth/users#signup', badge_id: 1, model_name: 'User' do |user|
        user.persisted?
      end
    end
  end
end
</pre>

merit.rb
<pre>
Merit.setup do |config|
  # Check rules on each request or in background
  config.checks_on_each_request = true
Merit::Badge.create!(
  id: 1,
  name: "Badge",
  description: "YEAH",
  custom_fields: { image: 'badge.jpg' }
)
</pre>

routes.rb
<pre>
  api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => "json"}, :default => true) do
    post '/signup', to: 'auth/users#signup'
end
</pre>

**Comment by tute** [comment]
I guess `before_action :authenticate_user!, except: [:login, :signup]` is trying to access `current_user`? Or something in the controllers.

Tip: you can use syntax highlighting with ````ruby`:

```ruby
a = 1 + 2
b = a *2
```

**Comment by jpaulo** [comment]
Thank you very much for the tip! I don't use github a lot, but i am learning!
And no, it is not the before_action that is calling current_user since before_action is excluding the signup action.
If i comment out the grant_on part of the badge_rules.rb, it works fine and does not try to call current_user.

One thing though, if i add a byebug entry in the current_user method like this

```ruby
    def current_user
      byebug
      raise ForbiddenError if @current_user.nil?
      @current_user
    end
```

And fill @current_user myself, it works perfectly. The badge is granted and everything works fine.
Once again, thank you very much for your time. Sorry for all the newbie hahahahaha  :)

**Comment by tute** [comment]
Surprising. Do you have your code publicly available, so I check?

**Comment by jpaulo** [comment]
I am sorry but no. This is a private app in a private reposiroty. But that's ok. You've already helped a lot. I'll try to debug further and see what is going on. :)

**Comment by tute** [comment]
I wasn't correct in a previous answer: merit will always call `current_user` (https://github.com/merit-gem/merit/blob/master/lib/merit/controller_extensions.rb#L23). Merit expects that method to return a user or nil, but not to raise.

**Comment by jpaulo** [comment]
Spot on, @tute! When i remove the raise part, it no longer gives an error. Thank you very much!
Now it is showing a "WARN -- : [merit] no User found with id" but i'll try to solve this one by myself.

<pre>
D, [2016-03-28T18:54:21.871346 #32400] DEBUG -- :   User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 17]]
D, [2016-03-28T18:54:21.872555 #32400] DEBUG -- :   User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT 1
W, [2016-03-28T18:54:21.872858 #32400]  WARN -- : [merit] no User found with id 
</pre>

**Comment by jpaulo** [comment]
Finally, it worked! In the end, it all came down to remove the raise we talked about and go back to "itself" in the grant_on like this

```ruby
      grant_on 'v1/auth/users#signup', badge_id: 1, model_name: 'User', to: :itself
```

Thanks a lot, @tute. You are the man.

**Comment by tute** [comment]
Happy to help. :clap:
