### ISSUE TITLE
uninitialized constant Merit::PointRules (NameError)

### ISSUE THREAD

**Issue by bmatmentel** [merit-gem/merit#252]
Hi,
I am trying to use this gem and when I run:
`rails g merit:install`
I get this error
`.../gems/merit-2.3.3/lib/merit.rb:89:in block (2 levels) in <class:Engine>': uninitialized constant Merit::PointRules (NameError)
`

This is a legacy code so I am running for now ruby 2.0.0 with rails 4.0.4. I tried it with a later version of ruby (2.1.7) and older versions of merit, and I get the same error.

Any tips, help  or suggestions are very welcomed!

**Comment by bmatmentel** [comment]
I found a fix:
in the file `lib/merit.rb`
add a rescue `NameError` line for `PointRules`.

I would like to know from the Authors if this is the right approach?

**Comment by tute** [comment]
This was just fixed in master: https://github.com/merit-gem/merit/commit/c8441cf43cd755b193f15dfe10155cbd29d15fbc. Will soon do a patch merit release. Thanks for reporting!
