### ISSUE TITLE
Merit gem don't work with default scope

### ISSUE THREAD

**Issue by rahul100885** [merit-gem/merit#254]
Merit gem is difficult to use in multi tenant application by using default scope. http://railscasts.com/episodes/388-multitenancy-with-scopes

TargetFinder given nil target as default scope adds tenant_id as nil in sql query.

**Comment by tute** [comment]
Is it difficult now, or is it impossible? What would we need to change in order to make it work? Thanks!

**Comment by rahul100885** [comment]
Is it impossible since if you look at above video, default_scope is used for multi-tenant application. default_scope adds a condition to fetch records for current_tenant using Tenant.current_id which is set in around filter.

here is code,

```
#app/models/user.rb
has_merit
validates_uniqueness_of :email, scope: :tenant_id
default_scope { where(tenant_id: Tenant.current_id) }
```

```
#app/models/post.rb
default_scope { where(tenant_id: Tenant.current_id) }
```

```
score 2, on: "topics#create"

#Now when we add any block for rule like say,
score 3, on: "posts#create" do |post|
  post.tenant.enable_leaderboard?
end

score 1, on: "comments#create" do |comment|
  comment.commentable.tenant.enabled_leaderboard?
end

#OR

score 1, on: "comments#create" do |comment|
  current_tenant.enabled_leaderboard?
end

```


all above rules didn't get applied as Tenant.current_id nil, so TargetFinder#action_user will always be nil.

In above pull request I have just moved include of ControllerExtention from on_load to explicitly into application controller and above all rules worked.

**Comment by tute** [comment]
Multitenancy is app-specific. As much as you change the DB tables, I'd expect some code to need changes as well.

I don't plan to extend merit to account for multi tenancy, but I'd be happy to merge PRs that make your job easier.

This is not an issue with merit, so I will close it, but let me know if I can help you get there with your app.

Thanks!

**Comment by rahul100885** [comment]
Above changes passes all test cases, except it is not backward compatible. Is there a way other than mixin `Merit::ControllerExcetions`  on onload of `ActiveSupport.on_load(:action_controller) ` or if possible lets get paired on this issue, as this issue is not just with default_scope or multitenant application, it is for all value which are available through around filter.

**Comment by tute** [comment]
@rahul100885 are you making changes to Merit's clases in order to support multitenancy? In that case, can you add this line in your application in such a way that it works for you/

**Comment by rahul100885** [comment]
Yes I did it and it is working. But for long run it will be difficult to maintain specially with new developers, though I have forked gem but still.

**Comment by tute** [comment]
Rahul, I received your email, thanks for the appreciation.

Indeed it is more difficult to maintain forks than to use open source libraries. But I'm afraid that this is app-specific logic, that makes sense it be maintained by the team behind that app, and cannot be generalised and offloaded into an open source solution.

If you need help architecting and developing what you need, I work at thoughtbot, and we might be able to help you: https://thoughtbot.com/hire-us.

Thanks for your input!
