### ISSUE TITLE
How to display the leaderboard points?

### ISSUE THREAD

**Issue by waynerochford** [merit-gem/merit#256]
Hi, 

Great gem you have made.

I'm using this tutorial https://github.com/merit-gem/merit/wiki/How-to-show-a-points-leaderboard for the points leaderboard, but I'm wondering can you show me how to use it
For example this is what I have for displaying the badge for user registration and it works great.

```erb
<% current_user.badges.each do |badge| %>
  <li><%= badge.name %></li>
  <%= image_tag badge.custom_fields[:image], alt: badge.description %>
<% end %>
```

But what should be added for the leaderboard points based on the above example?

And for the `merit.rb` file I have this

```ruby
Merit::Badge.create!(
  id: 1,
  name: "Yearling",
  description: "Active member for a year",
  custom_fields: { image: 'lib.png'}
)

Merit::Score.top_scored(
  since_date: 1.week.ago,
  limit: 25
)
```

Which does not run when I include the code

```ruby
Merit::Score.top_scored
Merit::Score.top_scored(
  since_date: 1.week.ago,
  limit: 25
)
```

Any help is appreciated 

Thanks,

Wayne

**Comment by tute** [comment]
Hi! I updated your code samples.

Have you added the `config/initializers/merit_scores_override.rb` file to your project, with the contents described in the wiki?

How does it fail? Do you have an error message or stacktrace to share?

Thanks!

**Comment by waynerochford** [comment]
Thanks for the reply, 

Yes, I've added the merit_scores_override.rb. 

I just have no idea how to display the leaderboard on a given page e.g ( I'm not sure what to put in the <%  %> on a .html page.

I'm not at my workstation at the moment, but I'm just not sure how to display it as explained above.

Thanks :),

Wayne

**Comment by tute** [comment]
`top_scored` returns a list of `Score`s (same type as `Merit::Score.all`, for example). You'll need to iterate through them and get to the desired data you want to display in your ERB template.

**Comment by waynerochford** [comment]
I must be getting confused with my setup

In the **merit.rb** file I added the Score method see below

![merit rb](https://cloud.githubusercontent.com/assets/14316073/15937810/4ea1d692-2e68-11e6-8a94-e39e94118a6c.png)

Which crashes displaying this

![crash](https://cloud.githubusercontent.com/assets/14316073/15937867/8668ff1a-2e68-11e6-8ae6-de59dc4ebe81.png)

I guess this is the incorrect place to add the code Merit::Score.top_scored within the merit.rb file?

**Comment by tute** [comment]
The screenshots are useful, thanks!

That is surprising. What version of merit are you using?

**Comment by waynerochford** [comment]
merit (2.3.4)

**Comment by tute** [comment]
If you run the `Merit::Score` bit in the context of a view or controller, what error do you get?

**Comment by waynerochford** [comment]
Success!

Your idea of adding the code to the view worked.

So for displaying points and following your steps I added this code to a given view e.g (index.html.erb)

`<%=
Merit::Score.top_scored
Merit::Score.top_scored(
  since_date: 1.week.ago,
  limit: 25) %>`

![yis](https://cloud.githubusercontent.com/assets/14316073/15940734/4a1145d8-2e75-11e6-99b9-5d965ecceca5.png)

Thank you 😄 

Wayne

**Comment by tute** [comment]
🎉
