### ISSUE TITLE
Points for certain actions

### ISSUE THREAD

**Issue by waynerochford** [merit-gem/merit#257]
Hi,

I have implemented points whereby when a user is on a page they receive 20 points and it works fine.

`score 20, :on => 'attempts#show'`

I'm wondering is there a way to trigger points based on an action. For example I'm using this gem along with a quiz whereby each question has four options (See screenshot)

![gamifi](https://cloud.githubusercontent.com/assets/14316073/15940018/211da7fa-2e72-11e6-8d38-8a0f1c7c7625.png)

Do you have any idea how I could change the above code to where, if a user selects the correct option they receive 20 points?

Thanks,

Wayne.

**Comment by tute** [comment]
It will be something along the lines of:

```ruby
score 20, on: 'attempts#create' do |attempt|
  attempt.correct?
end
```

**Comment by waynerochford** [comment]
Hi,

Thanks for the reply, is there anyway I could use the point_rules.rb code within a helper class rather than a view?

**Comment by waynerochford** [comment]
<%= current_user.points 
                answer.option.text %>      
      <%= if answer.correct?
      current_user.add_points 10
      else
            current_user.add_points 0 
       end %>
      <% end %><%= current_user.points 
                answer.option.text %>      
      <%= if answer.correct?
      current_user.add_points 10
      else
            current_user.add_points 0 
       end %>
      <% end %>

:)
