### ISSUE TITLE
Rails 5 compatibility?

### ISSUE THREAD

**Issue by marcamillion** [merit-gem/merit#258]
I love the way this looks and I am interested in implementing this in my app, but just wondering if there are any potential Rails 5 compatibility issues, since I see nothing in the documentation about Rails 5.

Thanks.

**Comment by tute** [comment]
I haven't tried merit on rails 5 yet. I believe it should work, and if it doesn't it shouldn't be hard to support it. You can verify if it works adding version 5 to the build matrix in the travis.yml file. I am interested in seeing this work, feel free to ask for any help! Thank you.

**Comment by tute** [comment]
There are people running on v5. See https://github.com/merit-gem/merit/issues/173. Still interested in running tests against that version. Thanks!

**Comment by jrasanen** [comment]
```
~/.rvm/gems/ruby-2.3.0/gems/merit-2.3.4/lib/merit.rb:88: warning: already initialized constant Merit::AppBadgeRules
~/.rvm/gems/ruby-2.3.0/gems/merit-2.3.4/lib/merit.rb:88: warning: previous definition of AppBadgeRules was here
~/.rvm/gems/ruby-2.3.0/gems/merit-2.3.4/lib/merit.rb:89: warning: already initialized constant Merit::AppPointRules
~/.rvm/gems/ruby-2.3.0/gems/merit-2.3.4/lib/merit.rb:89: warning: previous definition of AppPointRules was here
rails aborted!
NameError: uninitialized constant ActiveModel::Serializers::Xml
~/.rvm/gems/ruby-2.3.0/gems/ambry-0.3.1/lib/ambry/active_model.rb:17:in `block in extended'
~/.rvm/gems/ruby-2.3.0/gems/ambry-0.3.1/lib/ambry/active_model.rb:10:in `instance_eval'
~/.rvm/gems/ruby-2.3.0/gems/ambry-0.3.1/lib/ambry/active_model.rb:10:in `extended'
~/.rvm/gems/ruby-2.3.0/gems/merit-2.3.4/app/models/merit/badge.rb:7:in `extend'
~/.rvm/gems/ruby-2.3.0/gems/merit-2.3.4/app/models/merit/badge.rb:7:in `<class:Badge>'
~/.rvm/gems/ruby-2.3.0/gems/merit-2.3.4/app/models/merit/badge.rb:5:in `<module:Merit>'
~/.rvm/gems/ruby-2.3.0/gems/merit-2.3.4/app/models/merit/badge.rb:1:in `<top (required)>'
~/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
~/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
~/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies/interlock.rb:11:in `loading'
~/.rvm/gems/ruby-2.3.0/gems/merit-2.3.4/lib/merit/model_additions.rb:38:in `_merit_define_badge_related_entries_method'
~/.rvm/gems/ruby-2.3.0/gems/merit-2.3.4/lib/merit/model_additions.rb:15:in `has_merit'
```


I keep getting this kind of errors on `rails db:migrate`, crashes to `NameError: uninitialized constant ActiveModel::Serializers::Xml`

**Comment by jrasanen** [comment]
Ok, resolved that one. Rails 5 doesn't include `activemodel-serializers-xml` by default, had to add it to Gemfile to get merit migrations to work.

**Comment by tute** [comment]
Thanks! Started testing against Rails 5 in https://github.com/merit-gem/merit/pull/260.

**Comment by tute** [comment]
This issue is coming from https://github.com/norman/ambry/pull/16
