### ISSUE TITLE
Sqlite to Mysql leaderboard

### ISSUE THREAD

**Issue by waynerochford** [merit-gem/merit#259]
Hi,

I've implemented the leaderboard using this tutorial https://github.com/merit-gem/merit/wiki/How-to-show-a-points-leaderboard via sqlite and it works fine. However if I change my database to sqlite3 to mysql2 or even from sqlite3 to Postgres the name and scores won't show.

This is what displays when mysql2 is used instead of sqlite3

![llll](https://cloud.githubusercontent.com/assets/14316073/16822932/1a801e7c-4958-11e6-9b98-cb3ae598341f.png)

This is what displays when Postgres (deployed straight to heroku) is used instead of sqlite3

![llb](https://cloud.githubusercontent.com/assets/14316073/16823723/fa7a9bba-495d-11e6-88d3-f711d41f09af.png)

Any ideas?,

Wayne.

**Comment by tute** [comment]
Does calling `values` on the result make it work? http://www.rubydoc.info/gems/pg/0.17.1/PG/Result#values-instance_method

**Comment by waynerochford** [comment]
Hi,

I'm not sure were to put or call values

Here is my merit_scores_overide.rb code

____________________________________________

`module Merit
  class Score < ActiveRecord::Base
    # Meant to display a leaderboard. Accepts options :table_name (users by
    # default), :since_date (1.month.ago by default) and :limit (10 by
    # default).
    #
    # It lists top 10 scored objects in the last month by default.
    #
    # This is a postgresql snippet, you may need to tweak it for other ORMs.
    def self.top_scored(options = {})
      options[:table_name] ||= :users
      options[:since_date] ||= 1.month.ago
      options[:limit]      ||= 10

      alias_id_column = "#{options[:table_name].to_s.singularize}_id"
      if options[:table_name] == :sashes
        sash_id_column = "#{options[:table_name]}.id"
      else
        sash_id_column = "#{options[:table_name]}.sash_id"
      end

      # MeritableModel - Sash -< Scores -< ScorePoints
      sql_query = <<SQL
SELECT
#{options[:table_name]}.email AS #{alias_id_column},
  SUM(num_points) as Total_Points
FROM #{options[:table_name]}
  LEFT JOIN merit_scores ON merit_scores.sash_id = #{sash_id_column}
  LEFT JOIN merit_score_points ON merit_score_points.score_id = merit_scores.id
WHERE merit_score_points.created_at > '#{options[:since_date]}'
GROUP BY #{options[:table_name]}.email, merit_scores.sash_id
ORDER BY Total_Points DESC
LIMIT #{options[:limit]}
SQL
      results = ActiveRecord::Base.connection.execute(sql_query)
      results.map do |h|
        h.keep_if { |k, v| (k == alias_id_column) || (k == 'Total_Points') }
      end
      results
    end
  end
end

__________________________________________

And how I'm displaying it on my index.html

`<%=Merit::Score.top_scored
Merit::Score.top_scored(
since_date: 1.week.ago,
limit: 25) %>`

**Comment by waynerochford** [comment]
Fixed :)

results.values
