### ISSUE TITLE
Searching through badges

### ISSUE THREAD

**Issue by waynerochford** [merit-gem/merit#261]
Hi,

Is there a way to **find a specific badge by name or id, description etc**?

Like if badge.id.get(2)?

Ideally I want to **separate all my badges** up **instead of this**  

```ruby
<% current_user.badges.each do |badge| %>

  <%= image_tag badge.custom_fields[:image] %>
   <%= badge.id %>
 <%=  badge.description %>
```

Any ideas,

Thanks,

Wayne.

**Comment by tute** [comment]
See `Badge.filters`:

* https://github.com/merit-gem/merit/blob/master/app/models/merit/badge.rb#L14

It uses https://github.com/norman/ambry#a-quick-tour.

Thanks!

**Comment by waynerochford** [comment]
Cool, solved it,

Thanks.
