### ISSUE TITLE
Removal of badges/points when using dependent => destroy in model

### ISSUE THREAD

**Issue by olliekav** [merit-gem/merit#264]
I'm trying to remove points and badges from Users if they delete records, but I can't work out/understand why deleting associated records doesn't run the BadgeRules?

So say I have a badge rule like this...

```*ruby
grant_on ['observations#create', 'observations#destroy'], badge_id: 1, temporary: true, to: :user do |observation|
        count = observation.user.observations.count
        count >= 1 && count < 10
end
```

An Observation belongs to a Location, and a User is able to delete a Location with all the Observations belonging to it, in the Location model this is set as `dependent => :destroy`. 

This works fine if a user deletes an Observation, the badges and points are removed, but why are the badge rules not being met when a Location is deleted? Are the actions set above not called on an associated record? Do I have to duplicate all the rules for `['locations#destroy']`?

**Comment by tute** [comment]
I think you'd need to add a rule like:

```ruby
grant_on 'locations#destroy', badge_id: 1, temporary: true, to: :user do |location|
  count = location.user.observations.count
  count >= 1 && count < 10
end
```

**Comment by olliekav** [comment]
@tute Okay, so I'd have to duplicate all the rules. I just wondered before I went that route if there was another way around it :) I'll give that a try. Thanks!

**Comment by tute** [comment]
If rules have exactly the same block (regardless of parameter) you can probably add `'locations#destroy'` to the first `grant_on` array.

**Comment by tute** [comment]
Thanks!
