### ISSUE TITLE
Rails 5 required belongs_to makes sash relation fail

### ISSUE THREAD

**Issue by tamycova** [merit-gem/merit#265]
Hi!
I just added merit to my app, when I try to seed users I get ActiveRecord::RecordInvalid: Validation failed: Sash must exist, should I manually add a Sash id when I create an user, or where does this problem come from?
Thanks!

**Comment by tute** [comment]
A User should create its Sash if it doesn't exist.
How do you seed in users?

**Comment by tamycova** [comment]
Thanks @tute  for the quick reply, this is how I seed:
User.create(first_name: 'Tamara', last_name: 'Covacevich',phone: '89378899', picture: '', password: '654321', email: 'tamy_cova@hotmail.com')

**Comment by tute** [comment]
This is the code that initializes a sash if it doesn't exist: https://github.com/merit-gem/merit/blob/master/lib/merit/model_additions.rb#L46-L56. I don't see why an application would need to manually create the sash.

Is this code you run in the console? If not, can you paste the file that contains that line? Can you paste your `User` model file?

Thanks!

**Comment by tamycova** [comment]
Yes! this is the code (when I run it directly in console it rollsback the transaction, if I add it in the seed then it raises a validation error, its not passing the has_merit validation in the user model). 
My seed:
<img width="509" alt="screen shot 2016-10-31 at 3 57 28 pm" src="https://cloud.githubusercontent.com/assets/11545206/19867589/22bfd0a6-9f83-11e6-8c1e-4d3945cc1417.png">
The error:
<img width="393" alt="screen shot 2016-10-31 at 3 57 21 pm" src="https://cloud.githubusercontent.com/assets/11545206/19867601/2f239f6c-9f83-11e6-8497-4337cc420f35.png">
What happents when I comment out the has_merit validation (sash_id goes to nil):
<img width="378" alt="screen shot 2016-10-31 at 3 45 35 pm" src="https://cloud.githubusercontent.com/assets/11545206/19867608/39124122-9f83-11e6-85e3-24d845863403.png">
This is my user model:

```ruby
class User < ApplicationRecord
    # Gamification
    has_merit

    # relacion de miembros user n:n group, OK
    has_many :members, dependent: :destroy
    has_many :groups, through: :members
    # relacion de admin user 1:n groups
    # podriamos poner dependant:destroy para que si se elimina el usuario grupo no quede sin admin -> futuro, OK
    # has_many :groups  
    # relacion de wheelers user n:n workouts, OK
    has_many :wheelers, dependent: :destroy
    has_many :workouts, through: :wheelers
    # relacion user 1:n places, creador, la logica de si es admin se ve en el controller, OK 
    has_many :places, dependent: :destroy
    # relacion user 1:n post, creador, dependant destroy -> future, OK
    has_many :posts, dependent: :destroy
    # relacion users 1:n comments, OK
    has_many :comments, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :phone, presence: true

    before_save :check_image

    def check_image
        begin
            url = URI.parse(picture) 
            Net::HTTP.start(url.host, url.port) do |http|
            res = http.head(url.request_uri)['Content-Type'].start_with? 'image' rescue false
            if not res
                self.picture = '/assets/default_user.jpg'
            end
        end
        rescue
            self.picture = '/assets/default_user.jpg'
        # https://www.apartmentadvisor.com/design/assets/tn3_userprofile.jpg
        end
    end

    def full_name
      "#{self.first_name} #{self.last_name}"
    end

    def reference
      "<a href='/users/#{self.id}'>#{self.first_name} #{self.last_name}</a>"
    end
end
```

**Comment by tute** [comment]
Thanks! And forgot to ask, what version of merit are you using?

**Comment by tute** [comment]
Aww this is biting us: http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html

Not sure how to fix right now, but that's the source of this bug in merit. Thanks for reporting!

**Comment by tute** [comment]
If it doesn't fail on previous versions of Rails, adding `, required: false` in the merit side (`model_additions.rb`) might be a good solution.

**Comment by tamycova** [comment]
Nice! I will figure it out in a while (have to leave now) and let you know how it goes!

**Comment by tamycova** [comment]
Adding `optional: true` to the belong_to association lets me seed and work perfectly with merit on my app (I changed the local installation). When I try to add the line to merit and run the tests with `rake` I get:
```
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib:test" -I"/Users/tamycova/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib" "/Users/tamycova/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
/Users/tamycova/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/tamycova/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/tamycova/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
```

I think it may be a version problem?

**Comment by tute** [comment]
Not sure. Is that the whole stacktrace you get?

You can also send a Pull Request, even if it's failing, so we inspect this in the Continuos Integration (Travis CI).

**Comment by tute** [comment]
Closing in favor of Pull Request. Thanks!

**Comment by AmitJoki** [comment]
Experiencing the same problem in Rails 5.1.4 while executing `@user.update`

**Comment by nikhilgoyal22** [comment]
@tute .. I see that pull request is closed ... so whats the solution of `ActiveRecord::RecordInvalid: Validation failed: Sash must exist.` when creating a user on rails 5.1.4

**Comment by redtachyons** [comment]
@nikhilgoyal22 try the changes in this PR https://github.com/merit-gem/merit/pull/287

**Comment by nikhilgoyal22** [comment]
@redtachyons  but what should I use in my gemfile

**Comment by redtachyons** [comment]
@nikhilgoyal22 
`gem 'merit', github: 'redtachyons/merit'` 

Add this in Gemfile and check
