### ISSUE TITLE
If you only intended to define PointRules you are in for a surprise

### ISSUE THREAD

**Issue by hugobast** [merit-gem/merit#267]
The way the engine hook is setup:

https://github.com/merit-gem/merit/blob/dc870272c1f68bf0e6e6669e27aa4a5675a3a855/lib/merit.rb#L88

Means that the error from BadgeRule being missing will cause PointRule to not be evaluated. Furthermore the way the rescue is designed we never see the error.

**Comment by tute** [comment]
Very true. Thank you! Would you send a PR addressing that?

**Comment by hugobast** [comment]
Yes I will! Thank you.

**Comment by hugobast** [comment]
Back from vacation, you can expect that PR today.

**Comment by tute** [comment]
Closing as the issue didn't reappear. Thank you for reporting it.
