### ISSUE TITLE
How to display flash messages on screen.

### ISSUE THREAD

**Issue by ltenzil** [merit-gem/merit#272]
How to display flash messages on screen. After giving a point or rank or badge. I don't want to send a mail. Thanks in advance

**Comment by tute** [comment]
As of now, you'd need to grant reputation manually (`current_user.add_badge(badge.id)`, `current_user.add_points(20)`) and then conditionally set the flash message all in your controllers, without using the `grant_on` or `score` APIs, which run after the controller action runs. Thanks for your question!

**Comment by ltenzil** [comment]
Hi @tute , greetings. i do know that. But can't we have those APIs in application controller in after filter. I like to have all badge and point related stuff in one place. I like those API's. its modularizes the code. I appreciate your work. Thank you for your time and efforts

**Comment by tute** [comment]
At the end of a controller action Rails redirects or renders, after which it calls the `after_action` callbacks. As of now it's not possible to add the flash message using current merit and Rails APIs.

A refactor we can do as a middle step is to expose as a public controller method Merit's `log_and_process` in such a way that users can call it manually on the endpoints they need, and then conditionally setting flash messages. We can test in the short term with current merit release using `send(:log_and_process)`.

This way you'd have to specifically tell your app where to compute reputation, but also you'd get the reputation rules defined in a single place, and the ability to change the rendered page to show the user a message.
