### ISSUE TITLE
question on how use to merit

### ISSUE THREAD

**Issue by benchow** [merit-gem/merit#273]
Hey guys,

I'm thinking of using Merit, in a StackOverflow like setup where a user can belong to and have a separate reputation in different networks.

My current schema is that a User has_many networks, through => memberships
Membership belongs_to  User and belongs_to Network.

using merit on the Membership model.
rails g merit Membership

Does Merit support this use case?  And, are there any gotchas I should know about to implement Merit this way?

**Comment by tute** [comment]
That will work well. You will need to configure `current_user_method` to be something like `current_membership`, so that Merit knows what object to add reputation to when running the controller `after_action` callback.

Let me know if you have other questions. Best!
