### ISSUE TITLE
Rails > 5.0 merit migrations gives exception for missing release number!

### ISSUE THREAD

**Issue by nimir** [merit-gem/merit#278]
Using Rails version 5.1.3 , after installing `merit` gem and running the install commands:
`rails g merit:install` and `rails g merit user`

When running `rails db:migrate`, following exception is thrown:

```
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateMeritActions < ActiveRecord::Migration[4.2]
```

This is due to missing release versions on generated migrations.
Will try to submit a PR.

**Comment by tute** [comment]
Thank you! :-) Closing in favor of the PR.
