### ISSUE TITLE
Badges in database

### ISSUE THREAD

**Issue by iamdriz** [merit-gem/merit#280]
Is it possible to store the badges in the database? Instead of having to declare them all in the `merit.rb` file.

**Comment by iamdriz** [comment]
And if an admin was to add a new badge it wouldn't require the server to be restarted. I was thinking of having a badge rules table that described which badges could be earned and how, and then in the merit rules models building the grants by looping through this data.

**Comment by tute** [comment]
I explained my rationale behind choosing Ambry to store badges in https://github.com/merit-gem/merit/issues/9#issuecomment-6367987. Storing them in the DB is a valid alternative, but that's not the path I chose for merit.

Thanks for your feedback.
