### ISSUE TITLE
If current user has a badge in list

### ISSUE THREAD

**Issue by iamdriz** [merit-gem/merit#281]
I have the following code which lists all the badges in my app:
~~~
<% Merit::Badge.all.each do |badge| %>
    <tr>
        <td><%= "<i class=\"icon-checkmark\" title=\"You achieved this badge on #{created_at}\"></i>" if badge.users ?? current_user.id %></td>
        <td><%= badge.name %></td>
        <td><%= badge.description %></td>
        <td><%= badge.users.count %> awarded</td>
    </tr>
<% end %>
~~~
What I want to show for each badge is if the current user has the badge. How can I check this?

Additionally while I'm at it, I also want to show the `created_at` date for when the user achieved it in the tooltip. I do something similar when displaying badges for a user like:
~~~
<% current_user.sash.badges_sashes.each do |bs| %>
    You achieved this badge on <%= bs.created_at %>
<% end %>
~~~

**Comment by tute** [comment]
There are two wiki pages that can help you with this. The key to your search is learning about the `merit_actions` table.

In https://github.com/merit-gem/merit/wiki/General-merit-workflow there's an explanation of how it is used.

In https://github.com/merit-gem/merit/wiki/How-to-show-last-granted-badges there's an explanation on how to query for the last granted badges. You can tweak code from there to fulfill your needs.

Please do share the code you arrive at, either in this issue or in the wiki. Thanks for your questions!

**Comment by iamdriz** [comment]
I've tried this:
~~~
module Merit
    class BadgesSash < ActiveRecord::Base
        def self.list_badges(options = {})
            all.map(&:user_badge)
        end
        def user_badge
            {
                user: User.find_by_sash_id(sash_id),
                badge: Badge.find(badge_id)
            }
        end
    end
end
~~~

Is that what you were thinking?

**Comment by tute** [comment]
Would this achieve what you seek?

```erb
<% Merit::Badge.all.each do |badge| %>
  <% badge_sash = current_user.sash.badges_sashes.where(badge_id: badge.id).last %>
  <tr>
    <td>
      <% if badge_sash.present? %>
        <i class="icon-checkmark" title="You achieved this badge on <%= badge_sash.created_at %>"></i>
      <% end %>
    </td>
    <td><%= badge.name %></td>
    <td><%= badge.description %></td>
    <td><%= badge.users.count %> awarded</td>
  </tr>
<% end %>
```

**Comment by iamdriz** [comment]
@tute Yep that's perfect! How can I prevent it from hitting the DB per badge?

**Comment by tute** [comment]
For now it's really good enough. If it starts to be a problem or you'd like to adjust it now, you can look into ActiveRecord's `includes` and `joins` calls. https://github.com/flyerhzm/bullet can help you spot the right place and syntax.

Thanks for your questions! Closing this issue now, but happy to continue the thread.
