### ISSUE TITLE
Add a dependent clause to improve efficiency

### ISSUE THREAD

**Issue by AmitJoki** [merit-gem/merit#283]
Let us say I have a badge `commenter-I`, `commenter-II` and `commenter-III` and the rules are such that whoever comments 5 times gets `commenter-I`, whoever comments 10 times gets `commenter-II`  and so on.

Now, it would be futile to look for the badge rules for `commenter-II` and `commenter-III` before `commenter-I` is granted.

So, it would be efficient if we had a `dependent` clause:
```
Merit::Badge.create!({
  id: 1,
  name: 'commenter-II',
  dependent: ['commenter-I']
});
Merit::Badge.create!({
  id: 1,
  name: 'commenter-III',
  dependent: ['commenter-I', 'commenter-II']
});
```
What we could do is check if the badges given in the dependent clause are granted on. Only if they satisfy the dependent badges we can check for the rules for the current one. This way, we could reduce checking rules.

**Comment by tute** [comment]
Thanks for your suggestion. I wouldn't define it as a property in the badge, but as a property in the reputation rules. And for that, we can use current syntax:

1. Add a model method that checks if the user has a badge

```ruby
def has_badge?(name)
  badge = Merit::Badge.by_name(name).first
  badges.include?(badge)
end
```

2. In the rule specify:

```ruby
grant_on 'comments#create', badge: 'commenter-II' do |comment|
  comment.author.has_badge?('comenter-I') && comment.author.deserves_badge('commenter-II')
end
```

I wouldn't add implementation and configuration options (both sources of complexity and potential bugs) for behavior that we can now implement.

Again, thank you for your suggestion, and if you think we should continue discussing we shall do so. Happy Friday!

**Comment by AmitJoki** [comment]
@tute I wasn't aware of `deserves_badge` method. Missed it in the docs I guess?  Anyway, this surely is easier than what I mentioned.

Thanks and Happy Friday to you too!

**Comment by tute** [comment]
That bit is an example of your application code, to show how it would be
done. Hope it’s good enough, if it’s not I’m happy to help! (May not be
online for days at a time though)
