### ISSUE TITLE
Override action_user?

### ISSUE THREAD

**Issue by Shpigford** [merit-gem/merit#291]
In my app I don't have a `User` model, I have a `Manager` model.

When I try to use `action_user` in badge rules and set `to: :action_user`, I get an `uninitialized constant User` error.

But if I set it as `to: :manager`, then I get...

    NoMethodError on `Member#manager` (called from Merit::TargetFinder#other_target)

Which is true...there's no `manager_id` on the Member object.

In application_controller.rb I've set up a `current_user` method:

```
def current_user
  current_manager 
end
```

Hoping that would bridge the gap, but no go.

So, was wondering if there's some way to tell `action_user` what _manager_ object it should be applying the badge to.

**Comment by tute** [comment]
You can use the `config.user_model_name` and `config.current_user_method` configuration options. See the initializer (https://github.com/merit-gem/merit/blob/master/lib/generators/merit/templates/merit.rb). Let me know if that helps!

**Comment by tute** [comment]
It seems we are lacking that documentation in the README.

**Comment by Shpigford** [comment]
@tute Yes! That did the trick. Thanks so much!
