### ISSUE TITLE
Merit being initialised once with Rails 5.2 and release 3.0.1 but for API and not Web app.

### ISSUE THREAD

**Issue by jamesjefferies** [merit-gem/merit#296]
The application I'm working on had an issue with Rails 5.2 and Release 3.0.1 where merit was being initialised once for the API set up, and then consequently not for the actual application set up. Consequently Merit doesn't work using the web infrastructure. 

Without the run_once, it does work, but of course you get the warning errors about Merit already being initialised!

If I get chance, I'll try and build an example application, but the fix which works (for me!) would be to change the ```ActiveSupport.on_load``` trigger from ```:action_controller``` which is used by the API and standard Rails infrastructure to a more specific ```:action_controller_base``` 

i.e.
```
ActiveSupport.on_load(:action_controller_base, run_once: true) do
```
This tightening of action controller loading is detailed a bit more here: 

https://github.com/rails/rails/pull/28402

**Comment by tute** [comment]
I believe that's the PR @truongnmt will contribute. Thanks for the context and help debugging!

**Comment by tute** [comment]
Closing in favor of your PR. Thank you James! 🎉
