### ISSUE TITLE
Dynamically changing scores based on user activity.

### ISSUE THREAD

**Issue by ccoeder** [merit-gem/merit#299]
Hi, 

I want to multiply scores based on user activity.  And i can calculate if they are active or not from their point in a daily basis. (See: https://stackoverflow.com/questions/21092422/merit-gem-how-to-grab-a-users-points-for-a-single-day)

So when user gains a point from a rule i want to multiply this point from their activity status. Like:

```
score 10, to: :post_creator, on: 'comments#create', do |comment|
  if current_user.is_active?
     comment.score * 2
  end
end
```

How can i do that? And sorry for my bad english.
Thank you!

PS: I apologize for the other post, I do not know how I shared it twice.

**Comment by tute** [comment]
Hi!

You could use a block to compute how many points should be awarded. See example from https://github.com/merit-gem/merit#examples-1. It will be something along the lines of:

```ruby
ten_or_20 = lambda { | comment| comments.post_creator.is_active? ? 20 : 10 }
score ten_or_20, on: 'comments#create'
```

Does this solve your need? Thanks!

**Comment by ccoeder** [comment]
Hi, 

Thanks, it solves my problem 😄 But i have another question, is merit works with api-only config? It does not work it.

**Comment by tute** [comment]
> Thanks, it solves my problem 😄

Yay!

> i have another question, is merit works with api-only config? It doesn't work it i think.

It should work, but you might be encountering a known issue for which there's this open PR: https://github.com/merit-gem/merit/pull/297. Feel free to contribute to the discussion, and even a fix!

---

Closing the issue as this is not a new bug in merit, but happy to continue the conversation.
