### ISSUE TITLE
Find by name returns all badges

### ISSUE THREAD

**Issue by seanfcarroll** [merit-gem/merit#308]
In my app I'd like to assign some badges directly, as the conditions are not triggered by a controller action, but rather a background process.

I would also prefer to assign the badges using a name, rather than an id, so was thinking to use something like:

```ruby
badge = Merit::Badge.find {|b| b.name == 'top-position-bronze'}
participant.add_badge(badge.id)
```

However, when I try the ```find``` command using a block, I am returned a hash of all badges. The way I define the badges [is here](https://github.com/crowdAI/crowdai/blob/6d666203f541f8fe51db6b0afe20328087e39889/config/initializers/merit.rb)

See an example of the problem from the console trace below. When I find with an ID it correctly returns the badge, while with find, it returns a merged hash of all badges. I have 24 badges in my main app, but to troubleshoot this issue, there are only 2 in the example below.

```ruby
(byebug) Merit::Badge.find(2)
#<Merit::Badge id: 2, name: "winner-silver", level: 2, description: "Awarded for winning 2 challenges", custom_fields: {:title=>"Challenge winner: Silver", :level=>"silver"}>
(byebug) Merit::Badge.find(1)
#<Merit::Badge id: 1, name: "winner-gold", level: 3, description: "Awarded for winning 3 challenges", custom_fields: {:title=>"Challenge winner: Gold", :level=>"gold"}>
(byebug) Merit::Badge.find{|b| b.name == "winner-silver"}
#<#<Class:0x00007f9770f1c868>:0x00007f97730c3598 @keys=[2], @mapper=#<Ambry::Mapper:0x00007f9773031238 @klass=Merit::Badge(id, name, level, description, custom_fields), @adapter_name=:main, @indexes={}, @lock=#<Thread::Mutex:0x00007f97730311e8>, @options={}, @hash={1=>{:id=>1, :name=>"winner-gold", :level=>3, :description=>"Awarded for winning 3 challenges", :custom_fields=>{:title=>"Challenge winner: Gold", :level=>"gold"}}, 2=>{:id=>2, :name=>"winner-silver", :level=>2, :description=>"Awarded for winning 2 challenges", :custom_fields=>{:title=>"Challenge winner: Silver", :level=>"silver"}}}>>
(byebug)
```

**Comment by seanfcarroll** [comment]
I should just add that this works:

```ruby
Merit::Badge.detect{|b| b.name == "winner-silver"}
```

But is the ```find``` method broken?

**Comment by tute** [comment]
@tachyons I see you are helping people in https://github.com/merit-gem/merit/issues/309. At first I thought this issue might have been related but it didn't seem like when I investigated a bit further. That said, I can't dig enough to make sure this is not a bug in merit or amber.

Does this thread seem like a bug in the code or the documentation to you? I'd close it, but I want to hear from @seanfcarroll (or another developer) first.

Thanks!

**Comment by seanfcarroll** [comment]
Ah OK, so **find** is a bit more like **where** in ActiveRecord. This can be closed.

**Comment by tute** [comment]
Thanks Sean! I'm still not a 100% sure this is not affecting #309 though. 😄

**Comment by tachyons** [comment]
https://github.com/norman/ambry/blob/master/lib/ambry/abstract_key_set.rb#L60 Though AbstractKeySet included Enumerable, #find is explicitly overrided there. So it must be an intentional but undocumented behaviour. #detect is not overridden. So it calls Enumerable#detect and returns single value.
I don't think this have anything to do with #309

**Comment by tute** [comment]
:+1:

It looks like funky behavior, but it's been like that for long now. Thank you!
