### ISSUE TITLE
Dynamic badges

### ISSUE THREAD

**Issue by nicholasrq** [merit-gem/merit#314]
Hi!

I just wonder if there's an option to have some sort of  "dynamic" badges?

For example I have badge "New country" that should be granted every time when user "visit" new country and I want to write which exactly country user visited but I don't wanna define badge for every single country like "new-country-italy", "new-country-israel", etc.

I noticed that there's `custom_fields` property on every badge but as far as I understand it just stores static data defined in `initializers/merit.rb` and I can't have here some unique data for each granted badge such as country id or something.

Ideally I want to have just one badge "new-country" that I can grant with unique properties for each user depending on rules, like:

user 1 has badge "new-country" with country ids 1 and 5
user 2 has badge "new-country" with country ids 6, 9, 28 and 75

**Comment by tute** [comment]
> I noticed that there's `custom_fields` property on every badge but as far as I understand it just stores static data defined in `initializers/merit.rb` and I can't have here some unique data for each granted badge such as country id or something.

Right. merit doesn't cover the use case in which you need dynamic badges. As stated in https://github.com/merit-gem/merit/issues/196#issuecomment-276083579:

> Merit [...] assumes badges data is static, and reliability of its code depends on that. Badges are versioned in git, alongside the rules that use them. Badges data live alongside the code in Merit.

---

It is possible to model merit with dynamic badges, but it would be a bit of a rewrite.

**Comment by nicholasrq** [comment]
Aha, I see. Thanks for the clarification.
