### ISSUE TITLE
Points and Badges awarded when controller action hits create even if editing a Record

### ISSUE THREAD

**Issue by psnider30** [merit-gem/merit#318]
The scenario is I have questions with many answers per user. I want to add a point or run a badge rule only if it is the first time answers#create is hit for a user on a specific question. I don't want to award anything after that since it would mean the user was editing answers. (what happens is old answers get destroyed and new answers get created on the question for a user.)

I need a way to look at Merit Actions and determine if there is a record already with the same target_id for the user. It seems like  check_all_rules in action.rb should be calling mark_as_processed! after checking the rules and not before, so I will try that approach.

I'm also looking for solutions anyone has found that address a similar situation to mine.

**Comment by psnider30** [comment]
We figured out an app specific way to work around this. I was able to add a foreign key to the merit_actions table. This way I could check the uniqueness of my record for a specific controller action.

**Comment by tute** [comment]
If this is a bug in merit I think we should still fix it. How can I replicate it? Do you have code I can read that triggers this problem? Thank you @psnider30!
