### ISSUE TITLE
score's :to argument

### ISSUE THREAD

**Issue by RonWalker22** [merit-gem/merit#320]
I'm using Operator Model instead of User Model. Without `:to` score works fine. With `:to` the operator doesn't receive any points and no errors are displayed. Within my app `mode.author` returns the author

doesn't work
`score 1, on: 'modes#create', category: 'mode',  to: :author`

I have also tried the following:
```
class Mode
  def mode_author
    self.author
  end
end
```

`score 1, on: 'modes#create', category: 'mode', to: :mode_author`

**Comment by RonWalker22** [comment]
I have the following points rules. Out of all of them, only the first one, 'modes#create' doesn't work. Funny thing is 'modes#destroy' is working. 

```
      score 1, on: 'modes#create', category: 'mode', to: :author
      score 1, on: 'respawns#create', category: 'respawn', to: :author
      score 1, on: 'locations#create', category: 'location', to: :author
      score 1, on: 'levels#create', category: 'level', to: :author
      score 1, on: 'characters#create', category: 'character', to: :author
      score 1, on: 'games#create', category: 'game', to: :author

      score -1, on: 'modes#destroy', category: 'mode', to: :author
      score -1, on: 'respawns#destroy', category: 'respawn', to: :author
      score -1, on: 'locations#destroy', category: 'location', to: :author
      score -1, on: 'levels#destroy', category: 'level', to: :author
      score -1, on: 'characters#destroy', category: 'character', to: :author
      score -1, on: 'games#destroy', category: 'game', to: :author
```

**Comment by tute** [comment]
Looks like a bug if that's the case. Thanks for informing. How can I replicate it?

**Comment by tute** [comment]
@RonWalker22 how can I replicate this issue? Do you have an application where this bugs is showing, so I can debug? Thanks!

**Comment by RonWalker22** [comment]
A model with the name of Mode is the issue. 

To replicate just create a Mode model that references a user. Then test: 
`score 1, on: 'modes#create',  to: :user`

**Comment by RonWalker22** [comment]
I tested a new app and couldn't replicate the bug. It must have been an issue with my code.
