### ISSUE TITLE
Merit::BadgeRules has been removed from the module tree

### ISSUE THREAD

**Issue by psnider30** [merit-gem/merit#321]
ArgumentError (A copy of Merit::BadgeRules has been removed from the module tree but is still active!) [error]

I'm getting this error frequently while developing even if I edit a rails file unrelated to merit. I'm wondering if it has to do with the fact that I include Merit (module) in user.rb. Is that supposed to be necessary? Without it I get an undefined method for has_merit.

Has anyone had similar issues with the module tree?

**Comment by tute** [comment]
That's strange! How can I replicate this error? Do you have code in GitHub I can check, or can you paste the commit in which you introduce merit into your app? Thanks!

**Comment by psnider30** [comment]
Hi Tute. Sorry for late response. We were going to create an example app to keep our coded confidential, but the problem was on our end and already solved. We're not certain what fixed this for us, but we tried to avoid models loading in the badge_rules by using 'User'.constantize instead of User
