### ISSUE TITLE
Relation "sashs" does not exist AND relation "merit_scor_points" does not exist

### ISSUE THREAD

**Issue by marcodotcastro** [merit-gem/merit#323]
I followed all the steps of the readme configuration, however when executing any merit method the following error occurs.

`Usuario.last.add_points(20)`

> ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "sashs" does not exist)

**Comment by tute** [comment]
Hi @marcodotcastro. That's because your app is configured in a language for which Rails doesn't know how to pluralize `sash`. Adding this to an initializer or app configuration should fix it:

```ruby
# Change :en with your language
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular "sash", "sashes"
end
```

**Comment by marcodotcastro** [comment]
Of course, I forgot that detail. Thanks a lot for the help.

But I believe this is a bug, as I tried the same solution it did not work.

ActiveRecord :: StatementInvalid (PG :: UndefinedTable: ERROR: relation "merit_scor_points" does not exist)

**Comment by tute** [comment]
That would be (I think):

```ruby
# Change :en with your language
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular "sash", "sashes"
  inflect.irregular "merit_score_points", "merit_score_points"
end
```

**Comment by marcodotcastro** [comment]
I tried both

` inflect.irregular "merit_scor_points", "merit_score_points"`

` inflect.irregular "merit_score_points", "merit_score_points"`

**Comment by tute** [comment]
`  inflect.irregular "merit_score_point", "merit_score_points"`?

**Comment by marcodotcastro** [comment]
It worked. Thank you very much.
God bless your service.
