### ISSUE TITLE
Access current_user

### ISSUE THREAD

**Issue by marcodotcastro** [merit-gem/merit#324]
Hello, how to access current_user in * _rules?

**Comment by tute** [comment]
It's not possible yet. I tried to do it in a very old branch, but wasn't happy with the outcome: https://github.com/merit-gem/merit/tree/current-user-in-rules-issue-98

**Comment by tute** [comment]
See https://github.com/merit-gem/merit/pull/100 (we may continue discussing there, closing it here as duplicate). Thanks!
