### ISSUE TITLE
Assign badges to existing data

### ISSUE THREAD

**Issue by adrienpoly** [merit-gem/merit#329]
Hello 

First of all thanks for this great gem.
I was wondering what would be the best way to assign new badges category to users who already match the rule in the past.

Let's say I add a new badge and some of my users match the rules already. The observer linked to the `grant_on` method is not going to be called unless the user navigates again through this route.

I search for the issues and couldn't find any recommended approach. Do I have to manually test my rule for each user and manually add the badge? or is there a better way to benefit from the `grant_on` rules already defined?

thanks

**Comment by tute** [comment]
Hi! `grant_on` sets up an `after_action` on the controllers, so there's no way yet to invoke it elsewhere. A script to run the rules over each user to grant reputation accordingly is the best way for this task.
Thanks for asking!

**Comment by adrienpoly** [comment]
@tute thanks
Will do it like that
