### ISSUE TITLE
Display flash messages to notify users when they obtain badges/points

### ISSUE THREAD

**Issue by gabrielguerin** [merit-gem/merit#340]
Hello,

I was wondering how can I display flash messages to notify users when they obtain badges or points? I followed this tutorial [Getting notifications](https://github.com/merit-gem/merit#getting-notifications) however, from what I understand, this is not sufficient to display flashes as it is a method accessible only from controllers. I am pretty new to Rails and I could not find a tutorial on how to implement this with Merit. I am not sure what information I should post here but my `User` model `has_merit` and I have done the tutorial mentioned above.

Thank you in advance!

**Comment by tute** [comment]
Merit doesn't make that easy, you'd need to use manually `add_badge` in you controllers to set the `flash` there, instead of the `grant_on` APIs. See also: https://github.com/merit-gem/merit/issues/272#issuecomment-293099593. Best!

**Comment by gabrielguerin** [comment]
@tute do you have a more explicit example because I have already read this issue but did not really understand it? I have this badge for example:
```
Merit::Badge.create!(
  id: 2,
  name: 'contributor',
  description: 'User contributed 1 time to the community.',
  level: 1,
  custom_fields: {
    icon_tag: 'star',
    category: 'contributor'
  }
)
```
What method should I add in my controller to display a flash messages? Is it `users_controller`?

**Comment by tute** [comment]
You'd need to use `add_badge` in the `PostsController`, see those methods in: https://github.com/merit-gem/merit/#other-actions.

Somebody asked how to make it work with Observers in https://stackoverflow.com/questions/35707575/notifications-flash-message-how-to/35708575#35708575, but as you can see it's too complex to make sense.

Sorry I don't have a more specific example yet.

**Comment by gabrielguerin** [comment]
Ok thank you @tute for your help and quick reply. I will try with what you sent me, and I'll come back if I ever find an answer or need a little help. :)

**Comment by gabrielguerin** [comment]
Just to know: to display flash messages, is the observer necessary?

**Comment by tute** [comment]
> To display flash messages, is the observer necessary?

No, they run in different parts. All that you need should happen in the controller.

**Comment by gabrielguerin** [comment]
In my case, `badge_rules` becomes obsolete, am I right?

**Comment by tute** [comment]
That's right, yes. Not sure if it has to stay empty or you can delete it.

**Comment by tute** [comment]
Will close this issue as it doesn't map to a bug in merit, but feel free to continue the conversation. Thanks!
