### ISSUE TITLE
Deprecation warning: Expected string default value for '--orm'; got false (boolean).

### ISSUE THREAD

**Issue by burmashave** [merit-gem/merit#346]
I'd commented about this in another issue: installing `merit` in a new Rails 6 project produces these `thor` deprecation notices (3 of them):

`Deprecation warning: Expected string default value for '--orm'; got false (boolean).
This will be rejected in the future unless you explicitly pass the options 'check_default_type: false' or call 'allow_incompatible_default_type!' in your code
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.`

Not sure if it's coming from `merit` or one of its dependencies. Explicitly downgrading `thor` to a pre-1.0.0 version gets rid of the warnings:

`gem 'thor', '0.20.3'`

Related (closed) issue: https://github.com/erikhuda/thor/issues/538

**Comment by tute** [comment]
Thanks for reporting! Does this change make it go away, with any `thor` version? https://github.com/merit-gem/merit/compare/tc-drop-unused-option?expand=1

**Comment by burmashave** [comment]
Unfortunately that didn't work, but I just issued a PR that takes care of it. Thanks!

**Comment by tute** [comment]
Fixed through https://github.com/merit-gem/merit/pull/350. Thank you, @burmashave!
