### ISSUE TITLE
Missing index on merit_actions table for processed

### ISSUE THREAD

**Issue by adrienpoly** [merit-gem/merit#355]
I have been noticing some slow queries on Merit::Action find. Finds where in the range of 100ms whereas most of the simple queries would be in the range of a few ms.

The exact query is:
```sql
SELECT  "merit_actions".* FROM "merit_actions" WHERE "merit_actions"."processed" = $? ORDER BY "merit_actions"."id" ASC LIMIT $? 
```

After adding an index to the column `processed` the query time dropped drastically to an average 2ms

![Capture d’écran 2021-04-09 à 6 12 22 AM](https://user-images.githubusercontent.com/7847244/114127353-8f65ee00-98fa-11eb-9192-1e72304135ce.jpg)

Shouldn't this index be added by default during the install? Or should it simply be documented somewhere?

Thanks for this great gem

**Comment by tute** [comment]
Yes, it should! Thanks for your report. Do you want to send a PR adding the index to that migration's template? So new installations will carry it.

(I wouldn't take care of preexisting installations, as adding an index to a big table can be time consuming, and the developer should do it with care.)

**Comment by adrienpoly** [comment]
ok will send a PR shortly
