### ISSUE TITLE
Error on create merit_actions migration file

### ISSUE THREAD

**Issue by SchaferF** [merit-gem/merit#358]
I have encountered an issue when I'm trying to perform the rails db:migrate command.
It seem's that there is the following mistake into the CreateMeritActions migration file.
The add index instruction must be contained in the def Change right after the end of the create_table instruction, and not after the end of the def Change instruction.
See the following captures.

![Generated_Migration_File](https://user-images.githubusercontent.com/33865157/122682399-6e265580-d1f9-11eb-90a3-b7b42c34f469.PNG)

![Migration_File_Modified](https://user-images.githubusercontent.com/33865157/122682402-72eb0980-d1f9-11eb-89a2-91267f77b61b.PNG)

**Comment by tute** [comment]
https://github.com/merit-gem/merit/releases/tag/v4.0.3 released with this fix! Thanks for reporting.
