### ISSUE TITLE
Devise & Sign-in then trigger grant_on

### ISSUE THREAD

**Issue by sdean013199** [merit-gem/merit#364]
Hello,
I am a bit new to ruby on rails to begin with but I've tried searching google and the issues but no one has seemed to talk about logging in and triggering a badge.

So when a user logs in, I want it to check how long their account has been created for. If relevant then give them the badge.

The new user badge works fine, but I am just wondering how to get the sign in trigger to work. I receive a `[merit] no target_obj found on Rule#applies?`

Badge_rules.rb
```
def initialize
      # New user
      grant_on 'users/registrations#create', badge: 'New-Baker', model_name: 'User'

      # 1 month user
      grant_on 'users/sessions#create', badge: "Typical-Baker", model_name: 'User', to: :itself do |u|
        u.user.created_at < "2022-04-25 00:00:00" && u.user.created_at > "2022-03-01 00:00:00"
      end

      # 1 year user
      grant_on 'users/sessions#create', badge: "Eternal-Baker", model_name: 'User', to: :user do |u|
        u.created_at < "2021-05-25 00:00:00"
      end
      
    end
```

routes.rb
`devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }`

sessions controller (controllers/users/sessions_controller.rb)

```
class Users::SessionsController < Devise::SessionsController
    def create
        @user = resource # Needed for Merit
        super
    end
  end
```

Things that work:
If I only use `grant_on 'users/sessions#create', badge: "Eternal-Baker", model_name: 'User', to: :user` but then I am unable to put conditions as I would like but as soon as user signs in, they receive the badge.

**Comment by tute** [comment]
I think it might be because you use `u.user.created_at` on the second `grant_on` call, but it should be `u.created_at`. Please try it!

You could name the block argument `user` to make that clearer:
```ruby
    def initialize
      # New user
      grant_on 'users/registrations#create', badge: 'New-Baker', model_name: 'User'

      # 1 month user
      grant_on 'users/sessions#create', badge: "Typical-Baker", model_name: 'User', to: :itself do |user|
        user.created_at < "2022-04-25 00:00:00" && user.created_at > "2022-03-01 00:00:00"
      end

      # 1 year user
      grant_on 'users/sessions#create', badge: "Eternal-Baker", model_name: 'User', to: :user do |user|
        user.created_at < "2021-05-25 00:00:00"
      end
    end
```

**Comment by tute** [comment]
It could also be that `created_at` returns a `Time`-like object, whereas `"2022-04-25 00:00:00"` is a `String`.

If you are on Rails you could use syntax like `1.month.ago` to use comparable data types.

**Comment by sdean013199** [comment]
Thanks for the response!

I changed up my code quite a bit

routes.rb 

`  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }`

badge_rules.rb
```
# New user
      grant_on 'registrations#create', badge: 'New-Baker', model_name: 'User'

      # 1 month user
      grant_on 'sessions#create', badge: "Typical-Baker", model_name: 'User', to: :user do |user|
        user.created_at < 1.month.ago && user.created_at > 1.year.ago
      end

      # 1 year user
      grant_on 'sessions#create', badge: "Eternal-Baker", model_name: 'User', to: :user do |user|
        user.created_at < 1.year.ago
      end
```

Sessions Controller
```
class SessionsController < Devise::SessionsController
    def create
        @user = resource # Needed for Merit
        super
    end
  end
```

Although that did not change or fix anything.
When I log in, I receive this message still `[merit] no target_obj found on Rule#applies?`.
Although it works with any other controller like users#show, but I would not prefer a profile to be triggered in order to get a badge. It still seems weird that when logging in, it does not work even when overriding devise sessions itself.
which is custom made to show profiles of that specified user inside of a user controller I made, here is what it looks like:

users_controller.rb
```
class UsersController < ApplicationController
    before_action :authenticate_user!, except: [:show, :index, :followings, :followers]
    def show
            @user = User.find_by_username(params[:username])
            render :show
        end
end
```

**Comment by tute** [comment]
It's looking better! Now it may be because you don't need to specify `, to: :user` in the last two cases. You already get the `user` in the block, and adding that option is akin to calling it twice (`user.user`). Try that.

**Comment by tute** [comment]
It's looking better! Now it may be because you don't need to specify `, to: :user` in the last two cases. You already get the `user` in the block, and adding that option is akin to calling it twice (`user.user`). Try that.

I didn't see that yesterday to correct it in my snippet.

**Comment by sdean013199** [comment]
I also did more testing.
I called the model_name: 'Resource' and if I put for example resource.present? it will give me the badge after logging in. So I'm thinking something with the controller or model is an issue?
I cant call resource.created_at since that model does not have that attribute.

**Comment by tute** [comment]
Can I see your whole code somewhere in GitHub so I can further debug? I need to be able to replicate your issue.

**Comment by sdean013199** [comment]
Yes! I've sent you a invite as it is a private repo.

**Comment by sdean013199** [comment]
The badges are also meant to display on the profile, so once logging in you can also check the profile for badges or the console after logging for details.

**Comment by tute** [comment]
I tried debugging but I couldn't make it work in time. This may be a bug in merit.

The controller should read `@user = warden.authenticate!(auth_options)` I think, and we'd want to grant `to: :action_user`, and then we don't need the `model_name:` attribute, but ran out of time.

For now, please use `add_badge` manually in the controller. Thanks for reporting.

**Comment by sdean013199** [comment]
Okay, no problem. Thanks for attempting! Let me know if any fix for this
Closing issue now.

**Comment by chandranshu12** [comment]
Hi @serenuy ! We wanted to try out merit in our application. So, was just going through the issues list to see what I should be aware of. Yours was the first one.

For devise sessions controller, the resource is actually a session object and not the user object. `users` is just a namespace here. Once the session is created, it'll store :user_id in the sessions_hash which you can use to find out your user and see if it works.
