### ISSUE TITLE
Setting up a cron job for Badge&Points

### ISSUE THREAD

**Issue by shivamd** [merit-gem/merit#73]
If i set #checks_on_each_request to be false. How do I setup a cron job or heroku scheduler  to update badges/points. For the Rank class there is a method called check_rank_rules but what about points and badges?
Any help would be appreciated.

**Comment by gauravtiwari** [comment]
Hi @tute The last snippet of code you have provided here is not quite clear. 

https://github.com/tute/merit/wiki/How-to-set-rankings-(and-reputation-in-general)-in-the-background%3F)

``` Merit::Action.check_unprocessed``` (where this will go). How a background service like ActiveJob can interact with this (any best practices)? I have set ``` config.checks_on_each_request = false ```. 

Thank you

**Comment by tute** [comment]
That does need more detail. What background processing library are you hooking into ActiveJob? Can you share the code, so we work on your app, and document our findings? Thanks!

**Comment by gauravtiwari** [comment]
I am using **Sidekiq**. From what I figured out, I have added following so far (it seems incomplete): 

1. Created a background job
```ruby
class CheckUnprocessedMeritActionsJob < ActiveJob::Base
  def perform
    ActiveRecord::Base.connection_pool.with_connection do
      Merit::Action.check_unprocessed
    end
  end
end
```
2. In controller actions where I need this job to run, I added an after_filter for relevant actions: 
```ruby 
CheckUnprocessedMeritActionsJob.set(wait: 5.seconds).perform_later 
```

It seems that something is missing, may be because the documentation isn't clear about **"how this process works?"**

**Comment by tute** [comment]
That looks good to me, Gaurav. You can decide now how often to perform the task. It seems cleaner to me to put it in a rake task that you run as often as needed as part of a cron job (every 5 minutes, every hour, every day; you pick), and clean up the controller code.

If you'd like to improve the wiki with these findings I'll appreciate it very much.

Have a good day!

**Comment by gauravtiwari** [comment]
Sure. Rake task option sounds good. :+1: 

One question regarding rake task. *Say for example,*  if an action is used for awarding a badge and I am using a Background job (rake task) to award a badge. How would Merit know that this is the action that ran last and should be awarded a badge ? 

The ```after_filter``` process looks clear to me as merit has access to all objects (say for example ```comment```) but, not sure about how this works when we use a rake task.

**Comment by gauravtiwari** [comment]
Okay, I think i figured it out. https://github.com/merit-gem/merit/blob/master/lib/merit/controller_extensions.rb#L10

```ruby
 def log_merit_action
    Merit::Action.create(merit_action_hash)
   end
```

This will log the merit_action in database anyway. That's how it will have access to the resources it needs to execute a badge/point rule. Is this correct?

**Comment by tute** [comment]
That is correct!

**Comment by gauravtiwari** [comment]
Great @tute :+1: Thanks. I will add my findings to Merit Wiki

**Comment by tute** [comment]
Thank you too!
