### ISSUE TITLE
NameError: uninitialized constant Merit::AppBadgeRules

### ISSUE THREAD

**Issue by auxout** [merit-gem/merit#75]
Hi,

I'm trying to reset and recompute all badges data by following instruction show in wiki page
https://github.com/tute/merit/wiki#how-to-recompute-reputation-for-users-after-rules-change

but got errors on line calling Merit::Action.check_unprocessed

```
NameError: uninitialized constant Merit::AppBadgeRules
from /Users/tkc/.rvm/gems/ruby-1.9.2-p318/gems/merit-1.5.0/app/models/merit/action.rb:26:in `check_all_rules'
```

**Comment by mrsweaters** [comment]
@tute I am also experiencing this issue when I try to run `Merit::Action.check_unprocessed` using version 3.0.0.

<details>
<pre>
16:02:26 worker.1 | 2017-09-06T23:02:26.888Z 49784 TID-ov9vhfclk CheckUnprocessedMeritRulesWorker JID-fa938f9dbea7837910a4892c INFO: fail: 0.013 sec
16:02:26 worker.1 | 2017-09-06T23:02:26.888Z 49784 TID-ov9vhfclk WARN: {"context":"Job raised exception","job":{"queue":"default","class":"CheckUnprocessedMeritRulesWorker","args":[],"retry":true,"jid":"fa938f9dbea7837910a4892c","created_at":1504738521.566742,"enqueued_at":1504738946.874563,"error_message":"uninitialized constant Merit::Action::AppBadgeRules","error_class":"NameError","failed_at":1504738521.597552,"retry_count":4,"retried_at":1504738946.888003},"jobstr":"{\"queue\":\"default\",\"class\":\"CheckUnprocessedMeritRulesWorker\",\"args\":[],\"retry\":true,\"jid\":\"fa938f9dbea7837910a4892c\",\"created_at\":1504738521.566742,\"enqueued_at\":1504738946.874563,\"error_message\":\"uninitialized constant Merit::Action::AppBadgeRules\",\"error_class\":\"NameError\",\"failed_at\":1504738521.597552,\"retry_count\":3,\"retried_at\":1504738820.469132}"}
16:02:26 worker.1 | 2017-09-06T23:02:26.888Z 49784 TID-ov9vhfclk WARN: NameError: uninitialized constant Merit::Action::AppBadgeRules
16:02:26 worker.1 | 2017-09-06T23:02:26.888Z 49784 TID-ov9vhfclk WARN: /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/merit-3.0.0/app/models/merit/action.rb:26:in `check_all_rules'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.1.3/lib/active_record/relation/delegation.rb:39:in `each'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.1.3/lib/active_record/relation/delegation.rb:39:in `each'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/merit-3.0.0/app/models/merit/action.rb:18:in `map'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/merit-3.0.0/app/models/merit/action.rb:18:in `check_unprocessed'
16:02:26 worker.1 | /Users/nutbutter/sites/enroll-api/app/workers/check_unprocessed_merit_rules_worker.rb:6:in `block in perform'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
16:02:26 worker.1 | /Users/nutbutter/sites/enroll-api/app/workers/check_unprocessed_merit_rules_worker.rb:5:in `perform'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:199:in `execute_job'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/honeybadger-3.1.2/lib/honeybadger/plugins/sidekiq.rb:10:in `call'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-unique-jobs-5.0.9/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:169:in `block in process'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/job_retry.rb:97:in `local'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/rails.rb:42:in `block in call'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/reloader.rb:68:in `block in wrap'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/reloader.rb:67:in `wrap'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/rails.rb:41:in `call'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:215:in `stats'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/job_logger.rb:7:in `call'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/job_retry.rb:72:in `global'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:129:in `block in dispatch'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/logging.rb:44:in `with_context'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:128:in `dispatch'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:168:in `process'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:85:in `process_one'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:73:in `run'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:16:in `watchdog'
16:02:26 worker.1 | /Users/nutbutter/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
</pre>
</details>
The above log is from a Sidekiq job. I get the same error when I run `Merit::Action.check_unprocessed` from the console.

**Comment by mrsweaters** [comment]
`Merit::Action::BadgeRules` and `Merit::Action::PointRules` are defined however.

**Comment by mrsweaters** [comment]
I was able to work around this issue by adding the following to the top of the Merit initializer:

```ruby
Merit::AppBadgeRules ||= Merit::BadgeRules.new.defined_rules
Merit::AppPointRules ||= Merit::PointRules.new.defined_rules
```
